### ISSUE TITLE
USB keys verified with GParted are not recognized under Windows 10

### ISSUE THREAD

**Issue by Petrouchka** [linuxmint/linuxmint#103]
Please see at https://gitlab.gnome.org/GNOME/gparted/issues/32#note_417028
As the patch is not in libparted, it must be added in each distro.

**Comment by gm10** [comment]
You would have to go upstream with that (Debian/Ubuntu). parted itself is abandoned and only received teh occasional patch to keep it afloat, but in my experience it's super buggy with anything not standard, unencrypted ext2/4. It cannot even read the sizes of some of my USB sticks correctly. I don't use it at all anymore.

**Comment by Petrouchka** [comment]
This bug is solved in GParted 0.33.0 (tested in https://gitlab.gnome.org/GNOME/gparted/issues/32). Linux Mint is using GParted 0.30.0.

**Comment by gm10** [comment]
That's a GParted Live CD version you are quoting, no any package version. The fix is in parted 3.2-21, which is only in cosmic (Ubuntu 18.10) but didn't get back-ported to bionic (Ubuntu 18.04), Mint's base.

Theoretically Mint can override Ubuntu's packaging choices but I strongly doubt Clem is going to do that for a package like this, that's why I said you'd have to go upstream with this. And yes, their bug reporting system is annoying when you just want to remind them to bump a bug fix version to an LTS release. :P

**Comment by Petrouchka** [comment]
And I don't think Ubuntu will make a backport too. I'm making bug reports in Ubuntu lauchpad since many years and NONE of my reports have had answers or have been solved.

**Comment by gm10** [comment]
If you need this regularly you can also try to pull the required libraries off cosmic. I think it's just this particular one you need: https://packages.ubuntu.com/cosmic/libparted-fs-resize0 but probably best to pull the entire set, usually a bad idea to mix & match different versions from the same base source package.
