### ISSUE TITLE
Nonexistant printer

### ISSUE THREAD

**Issue by agillator** [linuxmint/linuxmint#105]
A user with Mint 18.3 and I, Mint 19.1, are facing a frustrating problem. On some programs the print dialog shows a 'printer' entry that is actually mythical. It does NOT happen with LibreOffice, CUPS, gwenview , GIMP and other programs. It DOES happen with atril and Bluefish with me and when he prints a JPEG file. HPLIP for HP printers has no affect. It did not happen when I used xubuntu. lpstat and avahi-browse do not report any unexpected printers. Specific programs are picking this up from somewhere. By the way, you can't print to 'printer' either, it is rejecting jobs. I have no idea where it comes from, but I would certainly like to get rid of it through some method other than a bigger hammer. Of course we can simply ignore it, but could it be hiding some deeper problem (like an error in a bank book of one cent, a bookkeepers nightmare)? Ignoring is a stopgap, not a solution.

**Comment by xenopeek** [comment]
I hope you manage to figure this one out. Closing it here. Should this still be an issue I suggest to take help from the [support forum](https://forums.linuxmint.com/viewforum.php?f=51) with troubleshooting the root cause. See also out [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/).
