### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by HYDR001** [linuxmint/linuxmint#110]
Linux Mint Tara 19 Xfce

If you put the computer to sleep then open it up again, the computer is unlocked for less than a second and then it requires a password. This is a security problem. It may only happen on lower end computers.

**Comment by xenopeek** [comment]
Considering age of this issue closing it here. If any can reproduce it on current version, further [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) would be useful to pinpoint the responsible component (e.g., I think of lightdm, slick-greeter, Xfce, X11 or the kernel as possible suspects). For example by testing on the same hardware if the same can be observed using Linux Mint MATE or Cinnamon instead of Xfce.
