### ISSUE TITLE
Mint19 install creates incorrect Grub configuration

### ISSUE THREAD

**Issue by raqua** [linuxmint/linuxmint#117]
I was installing Mint19 Cinnamon edition on Lenovo Ideapad U310 of my friend. 
Installation went well, but machine does not boot, because there is misconfigured Grub. 
/etc/default/grub file has this line inside
`
GRUB_CMDLINE_LINUX="ignore_bootid live-media-path=/multibootusb/linuxmint-19.1-cinnamon-64bit/casper floppy.allowed_drive_mask=0 ignore_uuid root=UUID=BBE1-27C9"
`
which then generates incorrect Grub config every time there is kernel upgrade, or grub update is run. 

I was able to fix it manually, but wanted to report it somewhere. Not sure if this is the best place though ..

**Comment by xenopeek** [comment]
Considering age of this issue and it's unclear who or what would have misconfigured grub, closing this here. Glad you were able to fix it.

**Comment by Corax26** [comment]
FWIW this happens when installing Mint from a USB drive managed by multibootusb. I think the Mint installer gets confused by the kernel parameters it is itself booted with. Editing `/etc/default/grub` in the installed partition from the live Mint session before rebooting is probably the best option.

**Comment by raqua** [comment]
Yes, it was the same with me. Multibootusb was somehow causing this issue.
