### ISSUE TITLE
Four problems, some of them perhaps cosmetic, all seemingly to do with drivers, with running Mint 19.1 Cinnamon in VirtualBox

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/linuxmint#122]
In Mint: System Settings -> Drivers, 'InnoTek Systemberatung GmBH: Virtual Box Guest Service' is reported as 'not working'. Call that **problem 1**.

**Problem 2**: 'do not use this device' is selected (within System Settings -> Drivers), and yet there is an option to '_continue_ using a manually installed driver' (my italics). That contradictory state of affairs (or representation thereof) confuses. I am _not using_ this device and yet I _can continue using_ it?

**Problem 3**: one can move the radio button from 'do not use this device' to, 'Continue using a manually installed driver', but seemingly one cannot _execute_ the change. 'Apply' remains greyed-out.

**Problem 4**. Having moved the radio button from 'do not use this device' to, 'Continue using a manually installed driver', one cannot move the radio button _back_ (one cannot move it back to  'do not use this device'). Why not? This too confuses.

Does everything else work? Yes, but considerably more slowly that I would expect. (There is considerable lag, even though the host and to a lesser exent the guest have plenty of resources. Also - but this seems both a separate problem and one more to do with Virtual Box than Mint - when booting is finished the Virtual Box pop-up menu disappears entirely and irretrievably.)

Host: Windows 8.1 x64
Guest: Mint 19.1 Cinnamon
Virtual Box: 6.0.6.

**Comment by xenopeek** [comment]
Considering age of this issue I hope you previously managed to find a solution or workaround. For help with [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) if this issue is still affecting current version it's better to use the [support forums](https://forums.linuxmint.com/viewforum.php?f=231) for that and only report it as an issue on GitHub if the responsible component is one developed by Linux Mint. If that is Driver Manager report it here: https://github.com/linuxmint/mintdrivers. I assume the problem here might have been misconfiguration of VirtualBox on the host (for example using graphics driver other than VMSVGA).
