### ISSUE TITLE
Cursor grabs windows & drags

### ISSUE THREAD

**Issue by nakinigit** [linuxmint/linuxmint#123]
Seemingly at random, when I click on a window to activate it, the window will consequently follow wherever the cursor goes, until I click the window again. From what I understand, this behaviour should only occur if an additional key is pressed (alt). This is undesired, but I can't seem to prevent it.

**Comment by xenopeek** [comment]
Hope you managed to find the cause. Otherwise this doesn't provide enough information to go on (is it some feature of software you have installed, is it an issue in Linux Mint developed software or in some other OS component or driver, or is a problem with the mouse or keyboard). For help with figuring out the cause of problems please first use the forums https://forums.linuxmint.com/. See also our [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/).

**Comment by nakinigit** [comment]
OK, I thought it was self explanatory. This is a stock install, with dual monitors. At the time I posted this, I did not see anything in the forums, most likely because I am at a loss for an alternative explanation for the problem, hence, failed search results. It is a random problem, will try to capture with a video.

**Comment by Lew-Rockwell-Fan** [comment]
It's not limited to mint. I have the same issue in Lubuntu 24.04 in the plain Openbox environment with a Logi trackball. I suspect the answer will lie either in a Firefox about:config setting  or in a different "mouse" driver.
