### ISSUE TITLE
Upgrade chromedriver version to match google-chrome 74 on LMDE-3

### ISSUE THREAD

**Issue by tntim96** [linuxmint/linuxmint#127]
Same issue as https://github.com/redhat-developer/che-functional-tests/issues/482, but on LMDE-3. Is this a downstream issue? If so where would I report that?

Running Chromedriver 73 with Chrome 74 gives the following:

```
Capabilities [{message=session not created: Chrome version must be between 70 and 73 
  (Driver info: chromedriver=73.0.3683.75,platform=Linux 4.9.0-9-amd64 x86_64), platform=ANY}] 
```

**Comment by smurphos** [comment]
The chromedriver in the official repos will be matched to the chromium version in the debian repos, which is normally a version or two behind google-chrome from the external repo

I guess if you are using google-chrome rather than chromium you'll need to manually install the matching chromedriver version - http://chromedriver.chromium.org/downloads

**Comment by xenopeek** [comment]
Thanks @smurphos. Closing this issue.
