### ISSUE TITLE
SDL apps change my monitor configuration

### ISSUE THREAD

**Issue by nico-onmap** [linuxmint/linuxmint#15]
I am running Linux Mint 18.3 with Cinamon on intel graphics (4th generation core i5-4590 with 
Intel® HD Graphics 4600).

I have 2 full-HD monitors in `extended` mode, both at `1920 x 1080` resolution.

It's working perfectly until I start an SDL-based app, like scummvm, dosbox (both installed using `apt-get install...`). Whenever I switch one of these apps to fullscreen using `alt+enter`, it goes fullscreen, but the monitor configuration is changed to `clone` mode, without asking me anything.

When switching back to window mode, it stays in `clone` mode so I have to open the monitor preferences and set the mode to `extended` again.

**Comment by xenopeek** [comment]
It's hard to say what if anything the Linux Mint developers can do about issues with SDL programs (as in, Linux Mint developers neither the SDL libraries nor the programs that use those libraries that you mentioned).  I'd suggest to take help with troubleshooting this issue on the [forum](https://forums.linuxmint.com/viewforum.php?f=225) and should the root cause be discovered to be a component developed by Linux Mint, to re-open an issue for that component. See our[ troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/).
