### ISSUE TITLE
Ship a .desktop file for Orca on MATE so it is shown in Preferrred Applications

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#170]
![image](https://user-images.githubusercontent.com/3955499/70995682-6603cc00-20d1-11ea-8b16-f36e01ef29f1.png)

https://github.com/linuxmint/linuxmint/issues/52
https://github.com/linuxmint/mint19.2-beta/issues/54
https://gitlab.gnome.org/GNOME/orca/issues/55
https://github.com/mate-desktop/mate-control-center/issues/183
https://github.com/mate-desktop/caja/issues/580

**Comment by xenopeek** [comment]
It's not shown there because Orca ships without a .desktop file and how MATE implemented that dialog is to look for a Orca .desktop file. There's a clear rationale for Orca not having a .desktop file: https://gitlab.gnome.org/GNOME/orca/commit/500d4ca4a984b17dcf3e83d4fa796ac62b9cae45. On Linux Mint MATE the screen reader is toggled by Alt+Mod4+S keyboard shortcut, regardless of what is set in this dialog.

If a file `/usr/share/applications/orca.desktop` is created with following in it the dialog will show Orca selected:
```
[Desktop Entry]
Name=Screen Reader
GenericName=Screen Reader
X-GNOME-FullName=Orca Screen Reader
Comment=Provide access to graphical desktop environments via synthesized speech and/or refreshable braille
Keywords=screen reader;speech;braille;
Exec=orca --replace
Icon=orca
Terminal=false
Type=Application
StartupNotify=true
Categories=GTK;GNOME;Utility;Accessibility;
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=orca
X-GNOME-Bugzilla-Component=general
NoDisplay=true
```
On the MATE issue it was suggested to have this file with the last line `OnlyDisplayIn=MATE` but that needlessly also shows Orca in the menu: https://github.com/mate-desktop/mate-control-center/issues/270#issuecomment-498697894.

**Comment by InfoLibre** [comment]
Solved in Linux Mint MATE 20.
