### ISSUE TITLE
Burning an AudioCD fails

### ISSUE THREAD

**Issue by jonpoveda** [linuxmint/linuxmint#173]
## Description

Trying to burn an Audio CD fails on Brasero, k3b and xfburn.

All apps are installed with all the recommened and suggested packages from Synaptic.

It was not working on LinuxMint Cinnamon 19.2 and still not working on the recent upgrade to 19.3. A month or two ago I made it work on a LinuxMint Mate 19.2 after changing permisions on `wodim`. The same approach does not fix this bug in Cinnamon version.

System information: https://termbin.com/atar

## Errors

- xfburn: Outputs the message "Failure: Burn run failed"
- Brasero: hangs for a while and then shows an error message
- k3b: (tail of the log)
```
Errno: 5 (Input/output error), write_g1 scsi sendcmd: no error
CDB:  2A 00 00 00 21 C0 00 00 1B 00
status: 0x2 (CHECK CONDITION)
Sense Bytes: 71 00 03 00 00 00 00 0A 00 00 00 00 0C 00 00 00
Sense Key: 0x3 Medium Error, deferred error, Segment 0
Sense Code: 0x0C Qual 0x00 (write error) Fru 0x0
Sense flags: Blk 0 (not valid) 
cmd finished after 21.271s timeout 40s
/usr/bin/wodim: A write error occured.
/usr/bin/wodim: Please properly read the error message above.
write track data: error after 20321280 bytes
Writing  time:   40.937s
Average write speed  66.2x.
Min drive buffer fill was 99%
Fixating...
Fixating time:   13.117s
/usr/bin/wodim: fifo had 511 puts and 321 gets.
/usr/bin/wodim: fifo was 0 times empty and 257 times full, min fill was 98%.
BURN-Free was never needed.
```
### Full logs

k3b using DAO mode: https://termbin.com/26id
k3b using TAO mode: https://termbin.com/ykpw
brasero audio-cd: https://termbin.com/ohb0
brasero burning a pre-generated image: https://termbin.com/1q5u

## Tried

- Adding user to group `cdrom`
- Changing group of `/dev/sr0` from `root` to `cdrom`
- Changing permisions on wodim, cdrdao and growisofs as suggested by k3b.
```
sudo chmod 4711 /usr/bin/wodim
sudo chmod 4711 /usr/bin/cdrdao
sudo chmod 755 /usr/bin/growisofs
``` 
- Setting permision `4711` also to `/usr/bin/growisofs`
- Changing group of `wodim, cdrdao and growisofs` to `cdrom`
```
sudo chown root:cdrom /usr/bin/wodim /usr/bin/cdrdao /usr/bin/growisofs
```
- Creating a cue/bin image and then burning it directly.
- DAO and TAO modes
- Simulations succeeded without any warning or error message in all apps.

Note: changing group and file permissions are necessary from a clean install to, at least, fix some of the issues while burning with k3b but it seems to have no effect on the particular issue its described. Nevertheless, they are added for completion.

**Comment by xenopeek** [comment]
I hope you managed to find a solution or workaround. Assuming LM19.2 was fully upgraded the major difference with LM19.3--for  software that could have impact on capability of 3 CD burners--is maybe the Linux kernel which contains most hardware drivers. LM19.3 used kernel 4.15 while LM19.3 used kernel 5.0. You can downgrade to kernel 4.15 series on LM19.3 (through Update Manager > View > Linux kernels) and that kernel series is supported for the lifetime of LM19.x.

If you're still having this issue and downgrading to Linux kernel 4.15 series doesn't help I suggest to take help with [troubleshootaing](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) it from the [support forums.](https://forums.linuxmint.com) first. The Linux kernel isn't developed or maintained by Linux Mint so the developers can't do much right now on this issue. If it turns/turned out the cause was a component maintained by Linux Mint you can reopen this issue here.
