### ISSUE TITLE
Adding program icons to bottom panel and then moving any to the right of Firefox results in panel not showing open windows.

### ISSUE THREAD

**Issue by Ferryfolk** [linuxmint/linuxmint#178]
Tested on Mate system upgraded from 19.2. Workaround: Right click on bottom panel and select Reset Panel. Then add program icons to bottom panel again - but do not re-arrange order. If you do the problem recurs.

**Comment by xenopeek** [comment]
This is a known quirk of mate-panel. It's reported on mate-panel here: https://github.com/mate-desktop/mate-panel/issues/943

What happens is the following:

- By default the panel has the following applets from the left side, all locked in place: menu, show desktop, 3x panel launcher, window list.
- Because the panel launchers and window list are all locked, you can't put a new applet in between them.
- Trying to drag an program icon there will instead drop its launcher to the right of the window list, causing the window list to collapse (as it dynamically sizes to available width) so it becomes invisible.

This is annoying and unexpected but unfortunate side-effect of how locked applets and the window list's dynamic size interacts.

The workaround is to first unlock the 3 panel launchers and the window list. Right-click the panel launchers and deselect Lock To Panel. Do the same for the window list but you need to right-click _just_ to the left of the window list. I'd suggest to then first drag the window list a bit to the right and then reorder your launchers as desired and then drag the window list back. Else you may collapse the window list again if you drop a launcher to the right of it accidentally. If that happens just drag the last dragged launcher a bit to the right should make the window list reappear. Once you have the launchers snugly fit in order drag the window list back.
