### ISSUE TITLE
When Titlebar buttons set to left, Disks still shows buttons on right.

### ISSUE THREAD

**Issue by Ferryfolk** [linuxmint/linuxmint#179]
This is an old issue which was present in Mate 19.2 and possibly earlier versions too.

**Comment by Petrouchka** [comment]
It seems to be solved now.

**Comment by Petrouchka** [comment]
But not with the welcome screen window :
![image](https://user-images.githubusercontent.com/3955499/71543475-69ba0d00-2973-11ea-8380-3fb033a4c0b5.png)

**Comment by Petrouchka** [comment]
Same problem with list of mirrors window :
![image](https://user-images.githubusercontent.com/3955499/71543522-2d3ae100-2974-11ea-9937-b3e2f42b012f.png)

**Comment by Ferryfolk** [comment]
Problem persists with Disks for me. I confirm Petroucha's report that this problem also occurs with Welcome Screen and Software Sources.

**Comment by Petrouchka** [comment]
I'm using this version of Disks :
![image](https://user-images.githubusercontent.com/3955499/71544884-a2161700-2984-11ea-8cca-99ee4d7d6aaa.png)

**Comment by Ferryfolk** [comment]
Petrouchka, Yes on left in the About Disks screen  Smart Data screen, etc - **but not on the main Disks screen**.

**Comment by xenopeek** [comment]
Linux Mint 19.3 MATE lets you configure button layouts through Control Center > Desktop Settings > Windows. I tested with both Marco and Metacity as window manager and Disks follows the configured button layout for both, also on the main window. (For Marco you have to change both button layout options.) The original issue is thus fixed on newer release.

For Welcome Screen and Software Sources the window controls stay on the right and that's because the GtkHeaderBar has a decoration_layout set with right alignment, blocking user preference to have left alignment. That's something that requires a change in these programs' source code.

It was easy to implement on Software Sources so I've done a PR for that: https://github.com/linuxmint/mintsources/pull/193

For Welcome Screen my GTK skills fall short; the Welcome Screen currently only has a close button—if I remove the decoration_layout (the line `<property name="decoration_layout">:close</property>` from the file `/usr/share/linuxmint/mintwelcome/mintwelcome.ui`) it unintentionally also gets a minimize and maximize button. I suggest to report an issue on mintwelcome about window controls not moving to the left: https://github.com/linuxmint/mintwelcome
