### ISSUE TITLE
apt install xserver-xorg-input-synaptics resulting in an error

### ISSUE THREAD

**Issue by RippieUK** [linuxmint/linuxmint#182]
few days old work Dell Latitude 7380 laptop with Linux Mint 19.3 Cinnamon. I noticed today that when i closed the laptop lid and only displayed via HDMI to my HansG external monitor that the mouse cursor would just move around on its own.
Unplugged all USB devices and only had power and HDMI cable plugged in. still same issue. removed the HDMI cable and it stopped. Put the HDMI cable back in and issue continued.
Looked for known issues in the release notes https://linuxmint.com/rel_tricia_cinnamon.php and it mentioned potential issues with touchpad. After confirming that 'libinput' driver was used using 'https://linuxmint.com/rel_tricia_cinnamon.php' i went on to try and install synaptics driver using the command mentioned in the URL above.
'apt install xserver-xorg-input-synaptics'

This gave an error:
$ sudo apt install xserver-xorg-input-synaptics
[sudo] password for xxxxxx:             
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 xserver-xorg-input-synaptics : Depends: xserver-xorg-core (>= 2:1.18.99.901)
E: Unable to correct problems, you have held broken packages.

two_dogs and orcus on #linuxmint-help helped me fix this.

Orcus mentioned he had exact same issue on a brand new 19.3 VM before and after upgrades but that running 'apt install xserver-xorg-core' followed by 'apt install xserver-xorg-input-synaptics' then worked.
two_dogs suggested after a few troubleshooting steps to run 'sudo apt install xserver-xorg-input-synaptics-hwe-18.04' and then reboot.

After the reboot i can not confirm that synaptics driver is installed and working and the cursor is no longer moving around on its own.

two_dogs asked me to run this command sudo apt update ; aptitude install -sy xserver-xorg-input-synaptics | nc termbin.com 9999 which output this https://termbin.com/8unl

Orcus and two_dogs both suggested to raise as a 19.3 bug since this was suggested as a fix on the release notes known issues.

**Comment by xenopeek** [comment]
Thanks for the report. One part of this is a mistake in the release notes which will be corrected. The packages to install would be `xserver-xorg-input-synaptics-hwe-18.04` or `xserver-xorg-input-evdev-hwe-18.04` and not as currently on the release notes those but without -hwe-18.04 at the end.

Please confirm you currently have `xserver-xorg-core-hwe-18.04` installed on your Linux Mint 19.3 and not `xserver-xorg-core`. With that confirmed, if you had already installed `xserver-xorg-input-synaptics-hwe-18.04`, rebooted and that didn't help then go ahead an uninstall that one again and try `xserver-xorg-input-evdev-hwe-18.04` instead (and reboot).

I don't whether the "if you experience problems with it" in the release notes also suggest this as a fix for the spooky behavior you describe. That may have a different root cause perhaps.
