### ISSUE TITLE
CAJA can't extract files from .PAK and .ARC archives and from some ZIP files

### ISSUE THREAD

**Issue by Petrouchka** [linuxmint/linuxmint#188]
In CAJA, when right-clicking on a .PAK or a .ARC file, the **Extract here** menu is missing. These 2 archive formats are not recognized.
https://github.com/mate-desktop/engrampa/issues/347

CAJA can't extract files from some ZIP files
https://github.com/mate-desktop/engrampa/issues/346

**Comment by Petrouchka** [comment]
I can extract all files from all LZH, ARC and ZIP archives with Midnight Commander.

**Comment by Petrouchka** [comment]
I can't open .PAK files too with CAJA.

**Comment by Petrouchka** [comment]
MATE team closed my bug report with a usual so nice answer :o(

**Comment by xenopeek** [comment]
Engrampa doesn't have support for .arc or .pak archive file formats. See https://github.com/mate-desktop/engrampa/blob/master/README. So whether the .arc or .pak files are embedded, those are not going to work in Engrampa without you programming support for them.

You maybe able to get Caja to run `arc x` or `unar` for files in these archive formats, as they have a mime type so you can set an open with action for them. I tried that shortly but could only get `arc x` open with action to extract files in my home directory instead of in the directory where the .arc file is located. Please take that to the [support forums](https://forums.linuxmint.com/viewforum.php?f=47) if you need further help with that.
