### ISSUE TITLE
XApp Status Applet - Multiple Update Manager Icons

### ISSUE THREAD

**Issue by hatchcliff** [linuxmint/linuxmint#193]
I'm running Linux Mint 19.3 Cinnamon on an AMD Athlon 64 X2 Dual Core Processor 5600+.

Others have reported problems with the XApp Status Applet, but I thought the following repeatable symptoms might be useful in tracking down the fault.

The applet is listed with a tick beside it, which I think means that it has been added to system tray as intended.  However, when I select it in the list the + button is not greyed out, inviting me to add it again.
![Applets](https://user-images.githubusercontent.com/39442554/71821813-02930b80-308b-11ea-96de-8fca8fe0a7fa.png)

If I press the + button, an extra Update Manager icon appears in the tray.  By pressing it multiple times I can get a whole string of them.
![System Tray](https://user-images.githubusercontent.com/39442554/71822053-c4e2b280-308b-11ea-8069-2456b191f5e3.png)

All these extra icons perform normally, that is they call up the Update Manager, not XApp Status.
I can remove them in Panel Edit mode, but strangely the system asks for confirmation to remove the 'XApp Status Applet', not the 'Update Manager Applet' (this applies to the original Update Manager icon as well as the extra ones).  So it appears that the system is confused about which icons belong to which applets.

**Comment by mtwebster** [comment]
Hi, many applets allow multiple instances to be placed on panels.  For instance, someone might want their window list applet to appear on all their monitors.  The same is true with this one.  Just because the + sign is still active doesn't mean it *wants* you to add more.

This is applet is not a 'mint update' applet, it's just a generic container that programs (such as the update manager) can use to place a status icon on the panel.  Ordinarily there might be a bluetooth icon, or other items there as well.
