### ISSUE TITLE
HFS+ disks are not automatically mounted

### ISSUE THREAD

**Issue by Petrouchka** [linuxmint/linuxmint#200]
When I put a Mac OS X CD-ROM into my DVD drive, it isn’t automatically mounted. I must type manually ‘sudo mount -t hfsplus /dev/cdrom /mnt’.

**Comment by xenopeek** [comment]
I hope you managed to solve this already. If not I suggest to take help from the [support forum](https://forums.linuxmint.com/viewforum.php?f=47) with troubleshooting this issue. If the root cause is found to be in a component developed or maintained by Linux Mint, this issue can be reopened.

As this issue wasn't related to mintsystem (which is a collection Linux Mint specific system tools and overrides) I moved it here.

**Comment by Petrouchka** [comment]
Lost in the :ocean: of bugs.
