### ISSUE TITLE
Flatpak system repo keeps getting re-enabled

### ISSUE THREAD

**Issue by ajgringo619** [linuxmint/linuxmint#202]
I have moved my **Flatpak** installation to my /home partition, using the user repo instead of the system repo. However, during some of the system updates, the system repo is re-enabled, which causes any new Flatpaks to be installed under /. Is there any way to permanently disable this "feature"?

**Comment by xenopeek** [comment]
This needs further troubleshooting to find out what is doing this. I suggest taking help for that from the [support forums](https://forums.linuxmint.com/viewforum.php?f=47) if you haven't already found a solution or workaround. If the root cause is found to be in a component maintained by Linux Mint this issue can be reopened.

**Comment by mtwebster** [comment]
Mintinstall and the package system we use (in mint-common) are more or less hardcoded to use the system installation at the moment, to mimic behavior of the default package manager.  It's probably getting re-enabled when the package cache is updated.

I'll take a look at making this a bit more flexible.  The specific things that probably re-enables it is the `mintinstall-update-pkgcache` program, which is run periodically by mintupdate.  As a workaround, if you were to not use mintinstall, you could edit this script to do nothing.  Unfortunately there's not really much else to do for the moment.
