### ISSUE TITLE
Old version of Firejail incompatible with Firefox

### ISSUE THREAD

**Issue by jr751** [linuxmint/linuxmint#204]
It has been recommended on several different websites that Linux Mint users should use Firejail to sandbox their Firefox usage to improve security. I tried to install it through Software Manager, but it doesn't work with Firefox. When you open the terminal and type "firejail firefox" to open a sandboxed Firefox it opens Firefox but when you type websites into the URL box and press enter nothing happens. It doesn't take you to the website requested. I read somewhere that you have to install the latest version from the Firejail website as that this bug was fixed in the latest version. Apparently, this issue is due to an old version of firejail that the current Software Manager installs. I would like for the Software Manager to be updated to have this latest version. My understanding is that downloading packages from websites is risky as opposed to downloading them from the Software Manager so it would be good if the latest version could be added so it can actually be used safely. The Software Manager currently installs version 0.9.52-2, but the Firejail website's long term support version is 0.9.56.2-LTS and the current version is 0.9.60.

**Comment by xenopeek** [comment]
Thanks for your suggestion. 

Software Manager is the program to install software from the repositories but doesn't play a part in what is available in the repositories. Hence transferring this issue here.

Firejail comes from the Ubuntu universe repository and indeed version 0.9.52 is available there and has not been updated for a long while: https://packages.ubuntu.com/bionic/firejail. While certainly downloading packages from random websites should be done with caution—who made the package? how do you decide whether they are trustworthy?—downloading a .deb file from a project's own website doesn't raise those questions. As workaround for the Firefox + Firejail issue you can download the .deb file from the "released packages" link on the Firejail download page: https://firejail.wordpress.com/download-2/. For Linux Mint 20 it looks like the Ubuntu universe repository will have Firejail version 0.9.62 or newer.

Taking this issue as suggestion to package a newer version of Firejail than is available through the Ubuntu package base repository currently. For more information about the workflow for suggestions see the [FAQ](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html).
