### ISSUE TITLE
New software, optimizations.

### ISSUE THREAD

**Issue by ghost** [linuxmint/linuxmint#205]
Please, update software available for installation, add more browsers (eg Chrome and Opera). Optimize program to use less resources (it currently uses 243 MB RAM while Gnome Software uses 118 MB).

**Comment by xenopeek** [comment]
Software Manager is the program to install software from the repositories but doesn't play a part in what is available in the repositories. Hence transferring this issue here.

Thanks for your suggestion. For more information about the workflow for suggestions see the [FAQ](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html).
