### ISSUE TITLE
youtube-dl is out of date; gives errors about TLS. No such problem in latest version.

### ISSUE THREAD

**Issue by ChelonianEgghead** [linuxmint/linuxmint#206]
Title says it all, the version of youtube-dl in the repositories is unusable apparently because of a change in Youtube's encryption. The newest version works fine, could you update the repos?

**Comment by xenopeek** [comment]
Thanks for your suggestion.

Software Manager is the program to install software from the repositories but doesn't play a part in what is available in the repositories. Hence transferring this issue here.

youtube-dl comes from the Ubuntu universe repository and indeed has not been updated for a long while: https://packages.ubuntu.com/bionic-updates/youtube-dl. youtube-dl comes with a builtin updater but that is disable on Ubuntu. However, when you run that it tells you where to download the latest version of youtube-dl which is here: https://packages.debian.org/sid/all/youtube-dl/download. Download the .deb file from a location near you and install it with GDebi (as offered by your web browser when clicking a download link there or by double-clicking the downloaded file in your file manager). The [youtube-dl website](https://ytdl-org.github.io/youtube-dl/download.html) offers several more ways to get the latest version but these are more involved than simply downloading the package from above link, as youtube-dl suggests you when asking it to self-update.

Taking this issue as suggestion to package a newer version of youtube-dl than is available through the Ubuntu package base repository currently. For more information about the workflow for suggestions see the [FAQ](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html).
