### ISSUE TITLE
Package cinnamon-screensaver-x-plugins won't install

### ISSUE THREAD

**Issue by meersjo** [linuxmint/linuxmint#226]
Environment: LInux Mint 19.3 Cinnamon edition; fresh install on amd64 platform.

Symptom: The package ```cinnamon-screensaver-x-plugins``` refuses to install, because it doesn't recognise the default installed version of ```cinnamon-screensaver``` as being higher than required.

```
root@foxglove:~# apt install cinnamon-screensaver-x-plugin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 cinnamon-screensaver-x-plugin : Depends: cinnamon-screensaver (>= 3.1.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

```
root@foxglove:~# dpkg -l cinnamon-screensaver
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version          Architecture     Description
+++-=======================-================-================-====================================================
ii  cinnamon-screensaver    4.4.1+tricia     amd64            Cinnamon screen saver and locker
```

I'm aware that ```cinnamon-screensaver-x-plugins``` is an Ubuntu package; but if Mint provides an updated version of ```cinnamon-screensaver``` I feel it's also their responsibility to provide a working version of the plugins.

I've not tested this, but it looks as if it might just be a glitch in dpkg's version comparison and it may be as simple as providing a rebuilt package with updated dependency.

**Comment by xenopeek** [comment]
It's not a problem with packaging or with dpkg's version comparison. The problem is cinnamon-screensaver 4.x isn't compatible with cinnamon-screensaver-x-plugin 3.x. `apt` doesn't make that obvious but if you install with `sudo aptitude install cinnamon-screensaver-x-plugin` you would get this clue:

> The following packages have unmet dependencies:
>  cinnamon-screensaver : Breaks: cinnamon-screensaver-x-plugin (< 3.9) but 3.6.1-2 is to be installed
> 

Running `apt show cinnamon-screensaver` shows you that indeed cinnamon-screensaver says it breaks cinnamon-screensaver-x-plugin (< 3.9).

This package is only usable with the much older Cinnamon version that's in the Ubuntu repository, not with the current version of Cinnamon. I'm not familiar with cinnamon-screensaver-x-plugin but if you need help with whatever functionality you're missing you could ask on the [forums](https://forums.linuxmint.com/viewforum.php?f=208).
