### ISSUE TITLE
Fix for problem with Evolution email client

### ISSUE THREAD

**Issue by wpshooter** [linuxmint/linuxmint#249]
Not sure that this is the correct place to report this and if not maybe someone who knows the correct place can forward this request to the correct parties.

Am getting (me and other users also) the following error on Evolution email:

**Error performing TLS handshake: Internal error in memory allocation**

This only occurs on the RECEIVING email function and not on the SENDING email function, which is still working fine.  My best guess is that this has something to do with authorization certificate for Evolution having expired and the ISPs like AOL do not have enough sense to realize this and contact Evolution developers to request an up-to-date certificate.  Thanks.

See postings regarding this issue on Linux Mint forums.

**Comment by xenopeek** [comment]
The issue is reported to the Ubuntu maintainers of Evolution: https://bugs.launchpad.net/ubuntu/+source/evolution/+bug/1876286

Evolution isn't packaged or maintained by Linux Mint, it comes from the Ubuntu 16.04 package base repository on Linux Mint 18.3 (which you're using). A user from Ubuntu also [commented on the forum](https://forums.linuxmint.com/viewtopic.php?p=1804646#p1804646) having the same issue so it's not Linux Mint specific. This isn't the right place to report this. See also our [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/). 

Other users have commented on the forum topic that Evolution works fine for them which makes it look like the email provider or email retrieve method (IMAP or POP) plays a role. 

For troubleshooting this issue I've suggested on the forum topic that somebody that has the issue retest it with Evolution installed from Flathub. If it is reproducible with that it is for sure an issue in Evolution and not with how Ubuntu packages it or any of the system libraries. In that case it becomes useful to also report it to the Evolution developers: https://gitlab.gnome.org/GNOME/evolution/-/issues
