### ISSUE TITLE
linux mint won't shutdown or reboot on kernel 5.3.0-53 and amd64

### ISSUE THREAD

**Issue by 0nvd0** [linuxmint/linuxmint#253]
whenever i shutdown or reboot my screen clears after showing the linux mint logo but the power light on my pc doesnt go out and i have to manually reboot my pc via the power button if i want to turn it on again. using kernel 5.3.0-51 i dont encounter this isssue.

**Comment by SimonIremonger** [comment]
@0nvd0   which linux mint version?  Recently installed?   I would (guess) mint 19.x ?
If I'm not mistaken, kernel 5.3 series is or will be deprecated, likely to offer kernel 5.4 LTS series now, try using that?
Similarly -- helpful to test Mint 20 boot stick and see if that encounters the issue (comes with 5.4.0-26 kernel).
If the issue can still be replicated on current kernel series then more information on your hardware configuration could be useful debugging....

**Comment by xenopeek** [comment]
Closing because no response to questions.

I hope you already managed to solve this issue. If you're still having this issue I suggest to first take help with [troubleshootaing](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) it from the [support forums.](https://forums.linuxmint.com/viewforum.php?f=49).
