### ISSUE TITLE
Hang up during shutdown

### ISSUE THREAD

**Issue by kbenware** [linuxmint/linuxmint#260]
Clean install Mint 20 beta XFCE on Acer Aspire X1900.  System shutdown properly until installation of Virtual Box.  Tried shutting down several times before uninstall of Virtual Box, then shut down properly.

Wiped machine, did another clean install.  Again worked perfectly until VB was installed.  Hung up consistently on the Mint Logo screen shutting down, until removal of VB.  In no case was VB configured for anything, just freshly installed.

**Comment by SimonIremonger** [comment]
@kbenware  Virtualbox in ubuntu-20.04/Mint-20 has now been updated to a 6.1.10 based package that should be automatically selected if installing in updated mint-20 these days.  Does this now fix the issue for you?

**Comment by xenopeek** [comment]
Closing because no response.

**Comment by flightmaker** [comment]
I think I may be able to contribute to this issue. Both of my Mint 20 computers (fairly old but reliable) desktop and laptop were frequently failing to shut down and power off properly, leaving me having to hold in the power button which I hate doing.
Google searching found me this config file:-
/etc/systemd/system.conf.d/50_linuxmint.conf
which sets a parameter called DefaultTimeoutStopSec to 10s. Since I changed the setting to 50s on 25th May both computers have shut down and powered off, properly, every time.

There is however an issue with this edit. The documentation in the file itself says "To override these values, create your own file in /etc/systemd/systemd.conf.d/60_custom.conf" but unfortunately I tried this and cannot get it to work so I leave 50_linuxmint.conf set to 50s.

Also I suspect that there is a typo in the above quote where
 /etc/systemd/systemd.conf.d/60_custom.conf
should be
/etc/systemd/system.conf.d/60_custom.conf
