### ISSUE TITLE
two monitor setting is broken since dbus update

### ISSUE THREAD

**Issue by pizdjuk** [linuxmint/linuxmint#262]
kernel:  4.15.0-99-generic #100~16.04.1-Ubuntu SMP
OS: Linux Mint 18.3, MATE
X server: HWE version
Hardware: Thinkpad T470s

1) Connect to a monitor, set the other monitor to "primary display", turn off the monitor of a notebook.

2) go sleep, disconnect from monitor 1, connect to monitor 2, with bigger resolution.

3) wake up. The screen is broken, and the mouse pointer is "desynchronized" in a sense of a position. I mean, that a pointer point to other point, that actual is.
It seems, that X server doenst receive the new resolution of a monitor.

It seems to be a problem since the latter dbus update. And I cannot roll back to an old version of dbus, I didnt find older packets.

**Comment by xenopeek** [comment]
You can look in /var/cache/apt/archives/ where you may likely find previous package versions. Run command `ls /var/cache/apt/archives/*dbus*` to find all packages. You will probably find dbus, dbus-x11, dbus-user-session and libdbus packages for each version.

Suggest you first run `grep " upgrade .*dbus" /var/log/dpkg.log` to find which dbus packages you upgraded. The output of that command shows date of the upgrade for each package, package name, old version and new version. From the last date of upgrades pick all the package names and old versions and then install those from above archives directory.

To downgrade I suggest you change to the /var/cache/apt/archives/ directory and then run command `sudo dpkg -i filename1.deb filename2.deb filename3.deb filename4.deb` or however many dbus packages you need to install.

As dbus comes from the Ubuntu 16.04 LTS "xenial" package base repository, this isn't something that can be fixed by Linux Mint. If you can confirm this is an issue with dbus you will have to report it upstream. Otherwise further [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) is needed to find responsible component. For that I suggest to use the [support forums](https://forums.linuxmint.com/).

**Comment by pizdjuk** [comment]
unfortunately in /var/cache/apt/archives there are no old versions more....
Do you know some place with old packages?

**Comment by xenopeek** [comment]
I don't know a public archive of all historical Ubuntu package versions. If you don't have Timeshift or other system snapshot tool configured, you could downgrade from your current 1.10.6-1ubuntu3.6 version to 1.10.6-1ubuntu3 version available on http://security.ubuntu.com/ubuntu/pool/main/d/dbus/. First run earlier mentioned `grep " upgrade .*dbus" /var/log/dpkg.log` command to find which packages you need, then search for `1.10.6-1ubuntu3_` (mind the underscore at end) on the linked page and you should likely find all those packages there. Download the i386 if you're running 32-bit; amd64 for 64-bit. If you don't know for sure what your install is run `inxi -S` to find out.

Mind that you should only use the 1.10.6-1ubuntu3 version for testing purpose. As you can read on https://changelogs.ubuntu.com/changelogs/pool/main/d/dbus/dbus_1.10.6-1ubuntu3.6/changelog there have been important security fixes since that version.

**Comment by pizdjuk** [comment]
Please, reopen. I did rollback and it didnt help. The issue is still there. So, dbus is not a problem.
The problem appears, when I switch between extern monitors with different resolutions.

**Comment by pizdjuk** [comment]
So, I found the faulty component. It is compton. To trigger the bug you need to have two displays with different resolutions and marco+compton set in the contro-panel->window-properties.

Marco or Marco+compositing work good

**Comment by xenopeek** [comment]
Thanks for sticking with it to figure out the cause. Marco + Compositing is the default so this should only impact those that change it. Compton comes from the Ubuntu focal repository so this is upstream of us and not something that can be improved (if that can at all be done with Compton) during beta.

**Comment by pizdjuk** [comment]
the feature of compton was, that with marco+compositing the system suffers on tearing, but with compton -- no. So I have a choice -- suffer the bug, or see the tearing, or dont use compositing and see the video fullscreen, because without compositing and in a window mode there is tearing. ahhh :/ xD

So the problems are:

1) compton bugs with display change, no tearing in videos
2) marco+compositing tearing, no bugs with display change
3) marco without compositing, no bugs with display change, tearing in windowed mode, no tearing in fullscreen
