### ISSUE TITLE
Screen Brightness automatically changes very low when AC adapter connected to my laptop.

### ISSUE THREAD

**Issue by KenchanPrfm** [linuxmint/linuxmint#264]
* OS Version
Linux mint 19.3 Cinnamon edition

* Kernel
5.4.0-37-generic

* Laptop
Panasonic Let'snote CF-NX4

* Problem
When I connected my laptop to AC adapter, screen brightness changes to very low level, and cannot do any control except for mouse pointer for a few minutes.
How can I fix this problem?
I saw the some logs in "/var/log/Xorg.0.log" like bellow.
**1. Change Brightness Manually**
[   109.562] [dix] EventToCore: Not implemented yet 
**2. Change Brightness Automatically(AC connect)**
[   109.562] [dix] EventToCore: Not implemented yet 
[   282.677] (II) modeset(0): EDID vendor "CPT", prod id 0
[   282.677] (II) modeset(0): Printing DDC gathered Modelines:
[   282.677] (II) modeset(0): Modeline "1600x900"x0.0   97.76  1600 1648 1680 1760  900 903 908 926 -hsync -vsync (55.5 kHz eP)

**Comment by xenopeek** [comment]
I hope you already managed to solve this issue. This may likely be a Linux kernel (which contains drivers for most of your hardware) or graphics card driver issue, neither of which are developed or maintained by Linux Mint. Right now this issue doesn't have information that would let the Linux Mint developers work on it. If you're still having this issue I suggest to take help with [troubleshootaing](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) it from the [support forums.](https://forums.linuxmint.com/viewforum.php?f=59). Hopefully this can be solved by making some configuration change or driver upgrade. If it does turn out to be caused by something in Linux Mint you can re-open this issue here.
