### ISSUE TITLE
Live system does NOT Power-Off/Reboot! Regression?

### ISSUE THREAD

**Issue by Geraustus** [linuxmint/linuxmint#265]
When I shut down the live system, the shutting down procedure hangs near the final step and does not Power-Off/Restart.
The only way to get out of this freezing is to press the power button for a couple of seconds or to remove the power supply of the laptop.
Tested with Mint 20 beta Cinnamon and Xfce.

Works as expected with Mint 19.3 Xfce.

Mint 20 beta: Last lines of the shutdown log on the screen follow. The system is then frozen.
Mint 19.3 Xfce: I cannot record this line because the laptop powers off or restarts. :-)

"Reboot" (Mint 20 beta, identical Cinnamon and Xfce)
...
[  OK  ] Stopped Create System Users.
[  OK  ] Stopped Remount Root and Kernel File Systems.
[  OK  ] Stopped Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
[  OK  ] Reached target Shutdown.
         Starting Shuts down the "live" preinstalled system cleanly...
[  OK  ] Finished Shuts down the "live" preinstalled system cleanly.
[  OK  ] Reached target Final Step.
[  OK  ] Finished Reboot.
[  OK  ] Reached target Reboot.

"Power-Off" (Mint 20 beta Xfce, probably identical in Cinnamon but not written down):
... same as above, last 3 lines:
[  OK  ] Reached target Final Step.
[  OK  ] Finished Power-Off.
[  OK  ] Reached target Power-Off.

Hardware:

Booted from multiboot USB pendrive (16 GB), created with YUMI-UEFI, containing:
"linuxmint-19.3-xfce-64bit.iso"
"linuxmint-20-xfce-64bit-beta.iso"
"linuxmint-20-cinnamon-64bit-beta.iso"

Laptop: HP Compaq 8510p. No problem with Power-Off/Reboot using Windows XP.

**Comment by xenopeek** [comment]
I hope you already managed to solve this issue. I can't say whether YUMI-UEFI played a role in this but most likely this is a Linux kernel issue with your hardware. The Linux kernel contains most of the drivers for your hardware. LM20 and LM19.3 use a different kernel version and sometimes a new kernel version may introduce new issues. The Linux kernel isn't developed or maintained by Linux Mint so right now this issue doesn't have information that would let the Linux Mint developers work on it. If you're still having this issue I suggest to take help with [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) it from the [support forums.](https://forums.linuxmint.com/viewforum.php?f=49). Hopefully this can be solved by setting some kernel parameter or upgrading to a different kernel version. If it does turn out to be caused by something in Linux Mint you can re-open this issue here.
