### ISSUE TITLE
album-data config files missing from package manager

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/linuxmint#266]
album program that builds html web page of photos is missing all the themes folder.    album-data.
Linux mint 20 cinnamon 64bit.   after 6/28/2020 updates.

**Comment by xenopeek** [comment]
Same as with your issue for namebench, album-data is removed from Debian testing because of issues and therefor not included in Ubuntu 20.04—the package base for Linux Mint 20—either. You can look up status of packages in https://tracker.debian.org/. if you're unsure whether a package came from Linux Mint repositories or Ubuntu repositories, you can run `apt policy packagename` on a system that still has that package available to find where it comes from.

**Comment by ChooChooAl** [comment]
I understand your comment but not how to comply, even though your links and apt command are great to have on hand.  I've always had issues with where a bug stems from, Debian/Ubuntu/developer/??     To me, the program album is in Mint 20, but the themes (album-data) are not.  I copied one over that I like and it works fine.  I get that something in the package might be broken but my one theme is not, thankfully.  
Thanks for your input, I'll try playing with the other 2 items I reported and see if I can see how you came to your results.

**Comment by xenopeek** [comment]
From your other issue I inferred you had this package album-data on 19.3 but not on 20. Hence I checked on 19.3 where the package came from: from Ubuntu 18.04. I then checked the Ubuntu packages database (https://packages.ubuntu.com/), found the package not available for 20.04 and afterwards checked on Debian tracker as mentioned before what might have caused Ubuntu to not import the package from Debian and found answer there.

I get that this isn't ready knowledge for you thus I suggested on the other issue to take help from the support forum for troubleshooting the cause before reporting, as the Linux Mint developers can't fix this one or on the other issue.
