### ISSUE TITLE
Mint 20 Cinnamon missing apps from 19.3

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/linuxmint#267]
puddletag and namebench don't show in package manager.   
Would be nice to have them included.   Not sure whose issue this is, may be the developer of apps or missing inclusion in repros.

**Comment by xenopeek** [comment]
Valid observation but for similar could you do more [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/), taking help from the support forum as needed. These programs came from the Ubuntu package base repository but have been removed from that for the Ubuntu 20.04 release (which Linux Mint 20 uses) because a) puddletag uses no longer supported Python 2 and Qt4 which have largely or fully been removed from Ubuntu 20.04 and therefor also puddletag; and b) namebench is not included in Ubuntu 20.04 because Ubuntu imports such from Debian testing and it was removed from that because it's no longer in development.

If you look at the issues on the puddletag project you'll find work was started last month to migrate puddletag from Python 2 and Qt4 to Python 3 and Qt5 and I think there is a plan to make an AppImage. So there is some hope for future solution. For namebench I don't know of a future solution.

**Comment by schnedann** [comment]
Same here for tortoisehg. 
1st: Why one is not warned when attempt to upgrade from 19 to 20? I would never did this, if I would have been warned
2nd: without tortoisehg its almost impossible to work with hg repositories. There is no other tool around with at least 50% of the features and some workflows e.g. patchqueues can't be emulated by using the provided commandline tools. I think for a Desktop oriented Distribution breaking the Userland is futile. And a productivity program to just disappear breaks functionality in a very hard way.
3rd: telling the users that Ubuntu's wrong decision is just rolled out to Mint users is of no help. What are people doing which need this stuff to earn a living?
