### ISSUE TITLE
LMDE 4 - Synaptic Package Manager wrongly flagging grub-pc as residual config

### ISSUE THREAD

**Issue by arehtykitna** [linuxmint/linuxmint#269]
I have observed this on two different machines with differing EFI implementations so it is not machine specific and 100% reproducible when installing LMDE 4 in EFI mode to an empty SSD/HDD with a fresh GPT. Automatic partition option is used in Calamares, nothing complicated and I leave untouched were grub is stored.

CSM/Legacy mode is disabled on both machines so there is no way the ISO booted in the wrong mode.

grub-pc is wrongly flagged residual by Synaptic Package Manager after installation.

The flagging is erroneous as removing grub-pc screws up grub2 settings in place on the machine. ALL settings are lost for grub, so next boot it's blue and grey, low resolution with no snazzy background or linux command line options being retained either.

I have no idea what changes are made to synaptic by whoever packages this for mint, so I have to report it here rather than upstream. I cannot find an entry for it specifically here on the mint github. Please triage appropriately and assign to whoever is responsible because I don't believe the email address in the package details reflects that accurately. Thanks.

dpkg --list | grep synaptic
ii  synaptic                              0.84.6mint1+debbie                  amd64        Graphical package manager

**Comment by Ammako** [comment]
> ALL settings are lost for grub, so next boot it's blue and grey, low resolution with no snazzy background or linux command line options being retained either.

When you purge grub-pc residual config and it asks if you want to remove grub, just say no. Residual config is removed, and grub remains intact.

**Comment by arehtykitna** [comment]
> > ALL settings are lost for grub, so next boot it's blue and grey, low resolution with no snazzy background or linux command line options being retained either.
> 
> When you purge grub-pc residual config and it asks if you want to remove grub, just say no. Residual config is removed, and grub remains intact.

It doesn't ask, it just removes grub

**Comment by Ammako** [comment]
Odd, in more recent installations of LMDE it does, at least for me. Maybe some kind of update to packages from debian's side improved this since July.

You could check to make sure whether it's an issue with mint's version of synaptic or not, by forcing debian's version instead (`sudo apt install -t buster synaptic`, may need to uninstall it first.)

It's definitely not correct behavior, but probably not a very high priority issue because residual config being present doesn't really break anything. I guess a workaround for you would be to backup grub config files, purge grub-pc residual config, reinstall grub-efi, and copy your config files back into place.

**Comment by arehtykitna** [comment]
> It's definitely not correct behavior, but probably not a very high priority issue because residual config being present doesn't really break anything. I guess a workaround for you would be to backup grub config files, purge grub-pc residual config, reinstall grub-efi, and copy your config files back into place.

Indeed, I'm leaving the residual alone as it's a tiny component anyway. I will double check if it still happens and expect you are right about it being fixed in the meantime but I only have the one machine now running LMDE4 as the laptop that ran it is beyond economic repair, a cap on the motherboard blew. It was clean and well maintained inside and out but very heavily used daily for over 5 years.

It's also not something I have been checking after applying updates to be honest as it wasn't top of my priorities either. Thanks for your input anyway. I'll close this now

**Comment by Ammako** [comment]
I just realized after reinstalling recently, it does remove `/etc/default/grub`. That actually solves one interesting point of confusion I've been having about grub on EFI, because that file didn't exist I was falsely assuming that grub-efi doesn't use it.

Thing is though that has never caused problems for me. It never broke anything and I never lost the mint grub theming either. Grub has had an update in recent months though, so nowadays if you remove residual config for grub-pc after installing, and then update the system, a new `/etc/default/grub` gets installed with the same default config as normal.

I would probably still keep this issue open though, because it could definitely cause important issues for someone who removed grub-pc residual config after having already applied important modifications to their grub config.

LMDE 5 will hopefully be coming sometime in 2022 too, and hopefully it won't be having that problem in the first place.
