### ISSUE TITLE
"Click here to add search engine" doesn't work with Firefox 78.0.1

### ISSUE THREAD

**Issue by KHeilen** [linuxmint/linuxmint#270]
Hello, Mint Dev team.

**Issue Summary:**
It quite seems as if adding 1-click search engines only works in Firefox 78.0.1, provided under Preferences => Search, the separate searchbar has been enabled and added to the iconbar.
It should, however, work as well, if the addressbar serves as searchbar and as addressbar.

**References:**
These 2 Linux Mint Forum threads:
1. [linux mint 20, Firefox 78 and broken add search engine](https://forums.linuxmint.com/viewtopic.php?f=90&t=323695)
2. [[BUG] Can't add search engines in FF 78](https://forums.linuxmint.com/viewtopic.php?f=47&t=323637)

Note, please: Though LM 20 is mentioned and FF 78.0, the reported issue affects all LM releases, which use Firefox 78.0.1 still. So the issue may have been introduced with FF 78; but it is still partially present in FF 78.0.1

[Brief explanation by user sueede](https://forums.linuxmint.com/viewtopic.php?p=1839826#p1839826)
[Illustrated explanation](https://forums.linuxmint.com/viewtopic.php?p=1840004#p1840004)

In case more details are needed, please, let me know.

**Result:**
Users, who use the addressbar for both functions, as addressbar and as searchbar, will not be able to add more 1-click search engines on Firefox 78.0.1.

Best regards,
Karl

**Comment by xenopeek** [comment]
There's no need to add the separate search bar; search engines can be added through the page actions menu. Here are the steps to add a search engine on Firefox 78.0.1:

1. In Firefox go to Preferences > Search > (at the bottom) [Find more search engines](https://www.linuxmint.com/searchengines.php);
2. On that page click the icon of the search engine you want to add (that isn't in your list of search engines yet);
3. Then on the right side of the Firefox address bar click the ••• icon to open the page actions menu and choose Add Search Engine.

Here's a short video to demonstrate the above steps: https://i.imgur.com/LE6xTAZ.mp4

What doesn't work is the **Click here to add {name} to your search engines** link on the Linux Mint search engines page. I don't know if that can be made to work with Firefox 78.0.1. Otherwise the text on those pages could be updated to provide instructions for using the ••• page actions.

**Comment by KHeilen** [comment]
Thanks, xenopeek, for closing another one of my knowledge gaps. I had not been aware of the steps, which you explained. - OK. So, this issue can be closed as solved. No bug involved.
