### ISSUE TITLE
Bluetooth is not working

### ISSUE THREAD

**Issue by jack9603301** [linuxmint/linuxmint#292]
@clefebvre I use the Linux distribution of linuxmint, but in the process of using, I found that the Bluetooth function of Linux in the actual link process, active disconnection occurs after the link, unable to maintain the link normally. Can there be a solution, or is it related to the hardware?

**Comment by xenopeek** [comment]
This is likely a hardware driver issue. For help with troubleshooting this I suggest to first use the support forums: https://forums.linuxmint.com/viewforum.php?f=49. You'll need to register an account before you can make a New Topic there. Do include your system specs so others have some basic information. If you're on Linux Mint 19.3 or 20 you can just open System Reports from your menu, got to System Information tab and click the Copy button there. Include the copied text in your topic on the forum. If you're on earlier version run the command `inxi -Fxxrzc0` on the terminal and copy the output yourself (through terminal's Edit menu, select all and then copy).

If it turns out it's not a hardware driver issue but an issue with Linux Mint's bluetooth configuration manager (blueberry), and issue can be opened on that repository.
