### ISSUE TITLE
X not starting on AMD R7-3700U CPU with AMD Radeon Vega 10 Graphics if booting from battery

### ISSUE THREAD

**Issue by babjak** [linuxmint/linuxmint#295]
On an Asus Vivobook 15 (F512DA-NH77, AMD Quad Core R7-3700U CPU, 8GB DDR4 RAM, 512GB PCIe SSD, AMD Radeon Vega 10 Graphics) the X window system will not start from battery (goes to black screen) on boot, but it will start just fine when the laptop is plugged in. The issue is deterministic, and can be readily observed with the default install.

It may have nothing to do with it, but the computer also prints the following error on every startup (on batteries and when plugged in):
![shot0003_edited](https://user-images.githubusercontent.com/11505029/91662955-c1d18200-eab3-11ea-973c-534b880f9531.jpg)

**Comment by xenopeek** [comment]
That's an annoying and curious issue. Likely will have something to do with Linux kernel or graphics drivers, not with software developed by Linux Mint. I suggest if you're still having this problem to take help with [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) and solving this issue from the [support forum](https://forums.linuxmint.com/viewforum.php?f=59). If it turns out this is caused by a Linux Mint component you can reopen this issue here with further information.
