### ISSUE TITLE
Preferred Applications > Removable media > Select an application for video DVD's > Handbrake (Fail)

### ISSUE THREAD

**Issue by PaulAndrewAnderson** [linuxmint/linuxmint#296]
On my NUC-PC with LMDE-4, it works as it has always worked; I insert a DVD in a USB DVD/CD drive, and when it's a DVD it auto launches Handbrake (and on music CD's it launches Asunder). However, on another NUC-PC, which had Mint 19X (all versions of them), and now has a fresh install of Mint-20; that unit will not keep the selection of Handbrake. It reverts back to Media Player on its own. I've tried every pathway that it can be saved as, but to no avail. I will select Handbrake from the drop-down: Fail! Then I will  select Other Application, and go to Handbrake from there: Fail. Even in the middle of ripping DVD's, after Handbrake closes, and I eject one DVD and insert another, nothing happens (not even Media Player launches). I have to right-click on the DVD's desktop icon, and select Open With Handbrake, every time. Odd! Anyone?

**Comment by xenopeek** [comment]
Hi, for help with [troubleshooting](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) this I think it's better asked on the [support forums](https://forums.linuxmint.com/viewforum.php?f=47). If it turns out the cause is a component developed by Linux Mint this issue can be re-opened with further details.
