### ISSUE TITLE
Calibre doesn't start in LM 20

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/linuxmint#314]
Calibre doesn't start in LM 20 Cinnamon. Is this version (4.99.4) too old ?

![Capture d’écran du 2020-10-18 18-59-42](https://user-images.githubusercontent.com/3955499/96377122-8aae5180-1183-11eb-8010-ad8e87262c4c.png)

https://forums.linuxmint.com/viewtopic.php?f=68&t=332731&p=1905689&hilit=calibre
https://forums.linuxmint.com/viewtopic.php?f=47&t=332873&p=1904246&hilit=calibre

**Comment by xenopeek** [comment]
Calibre comes from the Ubuntu repository. This is an upstream issue: https://bugs.launchpad.net/ubuntu/+source/calibre/+bug/1881500. It's caused by the Python3 recent update to version 3.8.5. Calibre 4.99.4 works fine with previous Python3 version 3.8.2. Ubuntu maintainer for Calibre probably needs to bump the Calibre version to 5.x make it work with newer Python3 version.

**Comment by xenopeek** [comment]
Upstream bug: https://bugs.launchpad.net/ubuntu/+source/calibre/+bug/1898904
