### ISSUE TITLE
Window controls of Disks is misplaced when they are at left

### ISSUE THREAD

**Issue by apandada1** [linuxmint/linuxmint#329]
OS: Linux Mint 20, Cinnamon Edition

The window controls of Disks is too much shifted towards left. This happens only when the window controls are placed at left. This also happens in when the window is maximized.

![screenshot](https://user-images.githubusercontent.com/3063132/97839293-e6421880-1d07-11eb-8ccc-17352fd4dec4.png)

**Comment by xenopeek** [comment]
The default width of Disks' left sidebar doesn't leave enough room for all window controls when moved to the left. Disks is a Gnome program and Gnome has window controls on the right and even if moved to the left Gnome doesn't have minimize/maximize buttons so that default width makes sense. Solution: with your mouse grab the vertical line separating the left sidebar from the rest of the window and drag it a bit to the right to increase the width of the left sidebar panel. If you hover your mouse cursor over that line the cursor changes to a ↔ icon to show you can move that line.

**Comment by mtwebster** [comment]
This is an upstream bug.

ref: https://github.com/linuxmint/linuxmint/issues/280

**Comment by apandada1** [comment]
> Solution: with your mouse grab the vertical line separating the left sidebar from the rest of the window and drag it a bit to the right to increase the width of the left sidebar panel. If you hover your mouse cursor over that line the cursor changes to a left_right_arrow icon to show you can move that line.

This is not permanent. The same issue comes back when it is started the next time.

Unfortunately, GNOME devs do not seem to be interested in fixing bugs that do not affect GNOME (for example, Cheese has a [bug]( https://gitlab.gnome.org/GNOME/cheese/-/issues/62) that affects all non-GNOME DEs (including cinnamon) and its [patch](https://gitlab.gnome.org/GNOME/cheese/-/merge_requests/34) has been proposed for months, and it is not being merged (the developers even did not bother to comment). Recently Ubuntu [patched it](https://bugs.launchpad.net/debian/+source/cheese/+bug/1879183) locally.)

Disks is shipped with Mint as a default software, and small but annoying issues such as this decrease the overall polish (the default user experience in Mint is still much better almost all other OS.). 

I would suggest to remove Disks from the default installation, and ship something else (maybe GParted) instead.

**Comment by clefebvre** [comment]
3.38.2+mint1
