### ISSUE TITLE
password input on sudo appears as asterisks

### ISSUE THREAD

**Issue by pizdjuk** [linuxmint/linuxmint#346]
If I run sudo, then the password input appears in a form of asterisks. Which is a little bit confusing and could be a security problem. Why the behaviour was changed?

I saw that the problem is a file /etc/sudoers.d/0pwfeedback. How can I assure, that after deleting this file it dont appear other time on a system update?

**Comment by xenopeek** [comment]
Deleting the file doesn't guarantee it won't be reinstalled on future package update (use dpkg -S to find which package owns a file). The behavior was changed a few releases back as to some it can look like the program is stuck when it gives no visual feedback while typing.

Instead of deleting system files just override the setting. You can do so by putting the line:

```Defaults !pwfeedback```

in a new file in your /etc/sudoers.d directory, that has a filename with later lexical order than the 0pwfeedback file (e.g. 99myconfig will be parsed after 0pwfeedback so will let you override it). Log out and log in may be needed to effect the change.

For future help with configuring your system you can use the [support forums](https://forums.linuxmint.com/).
