### ISSUE TITLE
xdf-email dont work properly with claws-mail and an attach

### ISSUE THREAD

**Issue by pizdjuk** [linuxmint/linuxmint#347]
doing

xdg-email --attach some-file

calls claws-mail (as it should), but claws-mail reports an error "File `  doesn't exist or permission denied"

As a result simple-scan cannot e-mail an attach.

**Comment by xenopeek** [comment]
xdg-email and claws-mail are both not developed or maintained by Linux Mint. For help with troubleshooting this I suggest to use the [support forums](https://forums.linuxmint.com/viewforum.php?f=47). If during troubleshooting it's determined the cause is a component maintained by Linux Mint this issue can be reopened here. See also our [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/).
