### ISSUE TITLE
Chromecast não funciona na versão 20 ou superior

### ISSUE THREAD

**Issue by gustaavo-co** [linuxmint/linuxmint#362]
Ao usar o navegador Google Chrome, ou o MKChromecast, ou qualquer outro tipo de programa ou extensão para reproduzir no Chromecast, simplesmente não funciona.

**Comment by xenopeek** [comment]
For help with troubleshooting you can use the support forums. We have a Portuguese forum: https://forums.linuxmint.com/viewforum.php?f=72. If during troubleshooting it's found to be caused by a component developed or maintained by Linux Mint you can open an issue here. See also our troubleshooting guide for more information: https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/. Collaboration on this GitHib project is in English.
