### ISSUE TITLE
Regular Problems in Mint when mirror server is not available - package sources, synaptic, timeshift not starting even not in terminal

### ISSUE THREAD

**Issue by Fanny2021** [linuxmint/linuxmint#368]
Hi, out there :-)
due to this problem I upgraded from Mint 18.3 to Mint 19.3 last year - and now the very same problem occurs again:

It started when I couldn't make updates any more (~2 months ago) and got this message "please change mirror server http://mirror.inode.at/linuxmint/packages is not available"
(Bitte zu einem anderen Spiegelserver wechseln http://mirror.inode.at/linumint/packages ist nicht erreichbar")

As I cannot open the package sources - what can I do?

When refreshing the update manager I got this error messsage:
"Not all package source indices could be downloaded ..... Failure to get http://mirror.inode.at/linuxmint/packag ... Release403 Forbidden .... The depot http://mirror.inode.at / linuxmint / packages tricia InRelease is no longer signed "

("Nicht alle Paketquellenindizes konnten heruntergeladen werden.....Fehlschlag beim Holen von http://mirror.inode.at/linuxmint/packag ... Release403 Forbidden.... Das Depot http://mirror.inode.at/linuxmint/packages tricia InRelease ist nicht mehr signiert.")

As I cannot open Synaptic - it makes it even worse.

Timeshift is also not opening (I have deleted and installed again, didn't help) ...

Why - if the mirror sever is broken down or whatever - LM cannot just suggest/implement another one for the time being to prevent of all these problems?
I don't really want to setup Linux Mint again as all the tiny things I have changed will disappear - its so much work to do...

**Comment by xenopeek** [comment]
> As I cannot open the package sources - what can I do?

Do you mean the Software Sources program won't open? Try starting it from terminal with command: `mintsources` (if there are any errors can you share them in English by running the command as: `LC_ALL=C mintsources`). In Software Sources you can select a different mirror to use.

It sounds like there is more wrong on your system from all the programs refusing to start. I suggest you take this to the support forums for help with troubleshooting this: https://forums.linuxmint.com/viewforum.php?f=47. Requires registering an account before you can make a New Topic there. I'm confident the forum members can help you figure out why these programs aren't starting. If it turns out the cause is a component developed or maintained by Linux Mint you can reopen this issue here.
