### ISSUE TITLE
mate-desktop and other MATE components installed by default on Linux Mint Cinnamon !

### ISSUE THREAD

**Issue by Lurux** [linuxmint/linuxmint#369]
I stumbled upon this, because MATE somehow started itself while I was using Linux Mint Cinnamon !

Inspection of the apt logs seemed to indicate these packages were installed with the system, so I verified on the live usb: these components are indeed part of the live image !

Installed components include mate-desktop, mate-panel, mate-menus, as well as "gir-", "lib" and "-common" variations for some of these.

**Comment by JosephMcc** [comment]
That is intentional. They are used as a fallback when Cinnamon crashes so that you still have a useable desktop. It gives you something to use so that you can troubleshoot or fix the problem. It's always been the case in Cinnamon. Until a few years ago it used gnome-panel and metacity instead. So it's meant to be there.

**Comment by Lurux** [comment]
Wow, I didn't know that !

That explains a lot. I guess cinnamon crashed for some reason, and I was so confused to see the MATE panel pop up in place of Cinnamon's one ! Anyways, thank you for the quick answer. :slightly_smiling_face:
