### ISSUE TITLE
Mint 19 Cinnamon (Nemo): Google drive loading takes a huge amount of time

### ISSUE THREAD

**Issue by jeroenst** [linuxmint/linuxmint#39]
I've added my google account to linux mint 19 cinnamon but when opening the google drive network folder there is a loading indicator at the right bottom which never finishes

**Comment by jeroenst** [comment]
After long waiting it works.. Maybe inform user of taking long time?

**Comment by boniatti** [comment]
up

**Comment by ZeryOs** [comment]
Up
Takes a lot of time. After half an hour didn't show me half of the files in the root directory. Not to even try inside folders because the process would start all over again.

**Comment by ryanlavine** [comment]
Has there been any development or resolution to this? I am having the same issues. I have 113gb in my Gdrive. Took quite a while to populate. And when I was looking at a folder with .jpgs, it showed an icon. Was wondering if there was a way to see the actual image.

**Comment by jeroenst** [comment]
I don't think anyone is caring about the bugs in this repo :'-(

**Comment by ryanlavine** [comment]
So are you still using it as slow as it is? Is there a contact person to ask via email or message? I am not extremely familiar with Linux yet.

**Comment by jeroenst** [comment]
No, I don't use it anymore. I just use Google drive in my browser. Also there are other tools to sync Google drive with a local folder. I used that before.

**Comment by xenopeek** [comment]
Anyone rested this on Linux Mint 19.2 Cinnamon? Some improvement landed in Nemo with this release that sped up local network directory browsing. Perhaps it also affects this.

**Comment by smurphos** [comment]
I normally use rclone for GDrive integration into nemo (which has been very quick in all Mint Cinnamon releases I've used it in since 18.2 IIRC). But I'll give Gnome Online accounts another try and compare the two. It was glacial last time I tried it. I don't think this was ever a Nemo problem per se - I think it's a Gnome Online Accounts issue.

**Comment by dwbapst** [comment]
It is not a Gnome Online Accounts issue. I am experiencing this issue myself, right now, on Mint 19.2 (Cinnamon). After some research, it appears that it is a gvfs issue, best explained here:
https://gitlab.gnome.org/GNOME/gvfs/issues/378

Basically the entire gvfsd-google code had to be over-hauled so it didn't try reading every google file when the drive is mounted. For those of us with several hundred gigabytes on their google drive, this means we'll never connect to our gdrive. 

The commit that fixes the issue is here:
https://gitlab.gnome.org/GNOME/gvfs/commit/63700b556522cb779fee9b7f45b869df6b178c68

And the merge is here:
https://gitlab.gnome.org/GNOME/gvfs/merge_requests/9

...which is part of gvfs 1.39.1, available in a release with gvfs 1.39.90-1.
https://launchpad.net/ubuntu/+source/gvfs/1.39.90-1

Which is Disco Dingo - the last stable Bionic-Beaver version of gvfs is 1.36, which is what I have on Mint 19.3. I'm very new to Linux (I was a Windows user up until a month ago), so apologies if I misunderstand, but I think this means this issue is going to continue for the foreseeable future, and won't get safely fixed in Linux Mint until a Disco Dingo version of Mint is released, right? UN-safely, I guess I could try to upgrade gvfs to its Disco Dingo release, but it sounds like that is a bad idea, so I cannot even confirm that this really is the fix for my own occurrence of the issue.

(And now I'm going to look into using rclone as an alternative... BTW thanks for Rhino-Cinnamox @smurphos ! )

**Comment by xenopeek** [comment]
Solid analysis @dwbapst. Linux Mint doesn't use Ubuntu development releases as package base so there won't be a Disco Dingo (Ubuntu 19.04) based Linux Mint. Unless a fix for this issue is backported to Ubuntu LTS 18.04 it wouldn't be fixed until Linux Mint 20 mid next year, which would be based on Ubuntu 20.04 LTS.

**Comment by dwbapst** [comment]
Ah, I didn't know about the long-term vs short-term releases in Ubuntu. That clarifies a lot for me, @xenopeek ! Definitely explains why my google searches for 'when is Linux Mint based on Disco Dingo going to come out' weren't going anywhere... :rofl: 

One option is back-porting, though, right? We can just request a newer package version be available on the back-port repo for Bionic, for use with the last long-term release? Would that be reasonable to do in this case with gvfs, or is it better (since it is not a security issue) to just use alternatives like rclone?

**Comment by xenopeek** [comment]
I don't know. I only see security updates for Bionic gvfs packages. Debian doesn't have gvfs in its backports repository (Ubuntu imports this package from Debian) and there's no backports repository for Ubuntu. Neither Debian nor Ubuntu have a bug report on this in their tracker for the gfvs-backends package (from where gvfsd-google is installed). Gvfs consists of 7 packages (gvfs, gvfs-backends, gvfs-bin, gvfs-common, gvfs-daemons, gvfs-fuse, gvfs-libs), with programs using its library maybe also needing to be rebuilt and/or retested. Backporting a patch is one thing but backporting a whole release is probably very involved. Installing the 7 gvfs packages from disco on bionic didn't work due to dependencies (system libraries are wrong version) so it would mean recompiling the software for bionic. I don't know that a fix will be happening for bionic.

**Comment by ijash** [comment]
i am experiencing this issue too

**Comment by xenopeek** [comment]
Closing this issue as it needs a newer Gvfs package and the needed version isn't likely to be backported considering impact on the package base. The package base for upcoming Linux Mint 20 (due mid this year) has a newer Gvfs package version where this should be fixed. I'm sorry I can't offer a workaround.

Thanks all for the help with diagnosing this issue.
