### ISSUE TITLE
Request: firefox-esr in Mint repos

### ISSUE THREAD

**Issue by ghost** [linuxmint/linuxmint#394]
Hiya, ESR already gets built by linux mint for LMDE, so how much work would it be to add builds for it into the regular Mint repos as well?

Only way to get ESR on Ubuntu base right now is via snap, or by downloading official Mozilla builds from their site and running them without installing (or build it yourself I guess.) None of those options are ideal.

I probably don't have to talk about snap, that would be the same deal as Chromium. The Mozilla builds work, but I've had issues with getting desktop notifications working on those (both Firefox and Thunderbird) which makes them kinda unusable.

I figured if they already get built for LMDE, it probably wouldn't be that much more work to make it available for regular Mint as well, just like Chromium. That would be one more step away from snap either way, which I think would be a good thing.

**Comment by xenopeek** [comment]
Thanks for making a suggestion for Linux Mint. You're a little behind with LMDE; the regular release of Firefox is built for all Linux Mint releases since LMDE 5. They all have the non-ESR release of Firefox.

Firefox ESR over time is less secure than the regular release. Not all bugfixes can be backported from the regular release, you're not getting the new security & privacy features that are added to the regular release for a long time and it doesn't get the same level of testing.

If despite that you want/need Firefox ESR you can add this official Mozilla PPA to your system: https://launchpad.net/~mozillateam/+archive/ubuntu/ppa. Simply add `ppa:mozillateam/ppa` on the PPA tab in Software Sources and then you can install Firefox ESR through your package manager.
