### ISSUE TITLE
Hibernate in my LMDE4 install is buggy

### ISSUE THREAD

**Issue by Wallby** [linuxmint/linuxmint#411]
NOTE: copied from https://github.com/linuxmint/cinnamon/issues/10272

```
 * Cinnamon version (cinnamon --version) -> 5.0.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) -> LMDE 4 Debbie
 * Graphics hardware *and* driver used -> "intel GPU" + "NVIDIA GPU", but no additional drivers installed (i.e. using default from installation)
 * 32 or 64 bit -> 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog -> [xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/6985441/xsession-errors.txt))
 ```

NOTE: as I cannot upload syslog.txt to github (I suspect it is too big), here is a link to "some file sharing service I found".. https://ufile.io/wvatzou0

**Issue**
Hibernate (called "slaapstand" for me) succeeded once thusfar (installed LMDE4 today). Other times it takes me to the login screen without first shutting down. The time that it did work it went to a black screen, then to the login screen (without mouse cursor and keypresses seemingly disabled) and then went into hibernate successfully). Another time it shut down, but then did not "resume" (i.e. firefox was open before, now it wasn't).
There is +- 16.75GiB of RAM and my swap partition is +- 18GB.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Configuration info, if applicable**

**Comment by xenopeek** [comment]
Hibernation on Linux can be spotty. Most often the cause of hibernation issues is with the hardware. For example that the power interface was designed with only Windows in mind, power management not fully supported by manufacturer on Linux or something else for which you'll need a workaround specific to your hardware (a newer Linux kernel, a different graphics card driver, some kernel parameter to pretend to be Windows towards to power interface and so on). It's unlikely that the cause of this is a bug in the software developed by Linux Mint so can't do much here if this isn't a generic issue reproducible on other hardware. See also our troubleshooting guide https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/.

For help with troubleshooting this issue please use the support forums: https://forums.linuxmint.com/viewforum.php?f=246. Include your system information (from the System Report tool, or use command `inxi -Frxxz`) and ideally look through your journal around the time you tried to hibernate for messages about hibernation. To get a, most likely, relevant extract from your journal use command `sudo journalctl --priority 3 --no-pager --since today` to show all errors from your journal from today (assuming you tried to hibernate on that day). You can select all text and copy it through terminal's Edit menu. With that system information and this information from your journal hopefully something stands out to those providing help with troubleshooting such issues.
