### ISSUE TITLE
Why was website-wizixo archived? I want to contribute

### ISSUE THREAD

**Issue by igoracmelo** [linuxmint/linuxmint#420]
README doesn't tell anything, so I thought I should ask here instead.
The Mint [new homepage repository](https://github.com/linuxmint/website-wizixo) was archived and I can't find any place telling the reason...

**Comment by xenopeek** [comment]
The repo is closed because it was only used for developing the design template. The actual website uses different technology and changes to the design repo would not at this point propagate to the main website.

Many talented UX designers and website developers answered the call back in July https://blog.linuxmint.com/?p=4116 to help on the design template. I don't know if more people are needed on the design team but if you're interested you can try contacting the email address mentioned there.
