### ISSUE TITLE
website: linuxmint.com.ua link name

### ISSUE THREAD

**Issue by lindevel** [linuxmint/linuxmint#421]
Unfortunately, for a reason unknown to me, the https://github.com/linuxmint/website-wizixo repository is archived, so I'll write here
I was examining the new design of the official Linux Mint website and noticed a small error on the page https://linuxmint.com/links.php, you translated the name of the Ukrainian-language site https://www.linuxmint.com.ua/ into Russian, this is not logical, use the official site name "Linux Mint Україна" or translate into English "Linux Mint Ukraine"

**Comment by xenopeek** [comment]
The repo is closed because it was only used for developing the design template. The actual website uses different technology and changes to the design repo would not at this point propagate to the main website.

When Linux Mint Україна started few years back, it titled itself "Linux Mint -- Украина" (see wayback machine). As you say, the website has since retitled itself but we weren't informed. I've shared the change with Clem and he will update the link.
