### ISSUE TITLE
Username on login desktop

### ISSUE THREAD

**Issue by Buderus** [linuxmint/linuxmint#439]
An unauthorized person, with the knowledge of how to change a password, can easily gain access to any mint desktop.  When Mint starts up, a sign in box appears and right above that sign in box is the user name.  The savvy user can reboot, hit shift/e/ then edit the line beginning with linux and change the last part from ro-----------  to rw  init=/bin/bash/F10.  Upon rebooting to root...enter passwd and the name that was above the login window.  Create a password, verify passwd, reboot.  Now the unauthorized person has access.

**Comment by xenopeek** [comment]
The username  on the log in screen does not expose information not otherwise accessible: when booting to a root shell one can ls /home or cat /etc/passwd to get the list of usernames on the system for example, or create a new admin account on the system. Fact is if you have files on your system that you don't want accessible to people with physical access to your computer you need to use some kind of file or disk encryption. Linux Mint offers two types of encryption at installation time (full disk encryption and home directory encryption).
