### ISSUE TITLE
usrmerge removes a much used program

### ISSUE THREAD

**Issue by lessharm** [linuxmint/linuxmint#457]
Hello linuxmint,

my System is LM 20.2 Cinnamon and I haven't merged my system until now (I have an upgraded system). Yesterday I ran the installation of usrmerge in terminal and saw, that it will remove my email program, the old opera 12.16, when I go on. I don't use it as browser, but the email part is still well and I use it since many years. I found in synaptic, that this opera version needs the gstreamer0.10-plugin-good package version 0.10.31-3+nmu4ubuntu2.16.04.3 (this is the only one from the list of packages to be removed, that opera needs). Is there a way to prevent the removal of that gstreamer-plugin-good and thus opera? As far as I can see, gstreamer-plugin-good does not need any of the other packages to be removed.

I thank you in advance for a possible answer and

best regards and thank's for this wonderful OS

**Comment by xenopeek** [comment]
The last release of [Opera 12 for Linux](https://ftp.opera.com/pub/opera/linux/1216/) was 12.16, released 8.5 years ago. It is not possible to install this on a new install of Linux Mint 20.x because the package depends on libgstreamer-plugins-base0.10-0 and this release instead has libgstreamer-plugins-base1.0-0. I've not been able to find that package in (currently supported) older releases so I can't even try to install Opera 12.

![image](https://user-images.githubusercontent.com/21159972/149214924-4d29633e-c2b3-45b9-91f0-4477eeb34633.png)

I think you installed Opera 12 + the gstreamer 0.10 packages on a (much) older release of Linux Mint and upgraded it in place to Linux Mint 20.2? I'm sorry to say but these are unsupported packages and from your description I take it these were built before usrmerge was considered and aren't compatible with it. This isn't something the Linux Mint developers can solve for you.

I'm closing this issue here. I suggest you may try taking help from the support forums, ask in the[ Software & Applications](https://forums.linuxmint.com/viewforum.php?f=47) forum. Before you can make a New Topic to ask for help you need to register an account.

From what I found on the forums, other fans of Opera 12 (as web browser) have moved on to Vivaldi. Vivaldi's CEO and co-founder was also the CEO and co-founder of Opera. You may find it a good spiritual successor. It also has a built-in email client. I don't know how it compares to Opera 12, just reporting what I've read from other Opera 12 fans on the forums.
