### ISSUE TITLE
Linux Mint 19 - Problem with sound selection in apps like Discord

### ISSUE THREAD

**Issue by Nightbr** [linuxmint/linuxmint#48]
Hey,

I run into an issue and I have troubleshot this during 3 days with Discord support and Discord Linux.

## Config 
* OS: Mint 19 tara
* Kernel: x86_64 Linux 4.15.0-29-generic
* DE: Cinnamon 3.8.8

## The problem
I have an audio card with my speakers and an headset Logitech G930. I want that my audio card with my speaker is the Default output and I want to set Discord on my Logitech G930.
![image](https://user-images.githubusercontent.com/4228646/43049378-423685b0-8df7-11e8-8a8b-f8849f0e6c7c.png)

And in Discord, I set my G930 as input and output
![image](https://user-images.githubusercontent.com/4228646/43049397-816e19dc-8df7-11e8-9448-4f053fe2da58.png)

But the sound is still on the Default output (Speakers). And if I change the Default input/output in the system to the G930, I have all my sound in my headset G930 including Discord. 

## More troubleshooting

I installed pavucontrol to see what's happening and have more control on sound channel.

1- Initial State
Default system output = Speakers
Discord output = Default
![default](https://user-images.githubusercontent.com/4228646/43049543-c9444676-8df9-11e8-9009-6822a21494f0.png)
+ When we are in conversation 
![image](https://user-images.githubusercontent.com/4228646/43049577-30476c18-8dfa-11e8-8831-6add6ef6d5a5.png)

2- Change Discord settings to G930
Default system output = Speakers
Discord output = G930
![g930](https://user-images.githubusercontent.com/4228646/43049552-f3c2e45c-8df9-11e8-85f0-0b5b1c2f82e9.png)
+ When we are in conversation
![image](https://user-images.githubusercontent.com/4228646/43049579-39304e4e-8dfa-11e8-84f9-f963d19a0057.png)

Pretty weird it didn't change to this

![image](https://user-images.githubusercontent.com/4228646/43049569-20575dd6-8dfa-11e8-975e-58768b01f62f.png)

If I change manually through pavucontrol it works like expected.

## More things

* If I change the Default system input/output throught sound settings, it reset all channel to this input or output. It should not override apps config I think.
* When I restart the computer, It reset all channel to the Default input/output.
+ The Default System input/output is always reset to my G930 headset (usb)

## What I tried to troubleshoot

1- I am in contact with Discord support (12 messages), after some digging, they redirect me to this https://github.com/simoniz0r/Discord-Linux-Client-Issues and to the Discord Linux https://discord.gg/discord-linux because Linux is not in the support scope.
2- I test in live CD: same problem
3- I made a fresh install of Linux Mint 19 (running on it right now): same problem
4- I ask some help in the Discord Linux and they trashtalk me because they are Linux Mint haters...

## Finally

If you need some logs and more debug, don't hesitate to ask! I know there is ALSA and pulseaudio and Apps like Discord use pulseaudio to route the audio channel, so I can't help dig this a bit deeper.

I hope someone will take this issue seriously and at least try to help on this.

Thanks for your great work and your help!

Regards,

Titouan

**Comment by Nightbr** [comment]
I tested this in Latest LTS Xubuntu and I have the same issue :/ seems to be the sound layer is pretty broken in Ubuntu based...

**Comment by xenopeek** [comment]
Hard to say if this is a Discord issue, Ubuntu issue or Cinnamon issue. Your 2nd comment makes it look like it is Ubuntu. Does it only happen with Discord though, or other applications as well? I'd suggest to take help from the forums with further troubleshooting to pinpoint the root cause and responsible component.

**Comment by SandorSzavost28** [comment]
Damn! Still same issue on 2021. Ubuntu 20.04,  And the weird thing is that I just realized because one of my game friends told me he can hear all my audio (not just my voice) through discord... So i did the same test you did @Nightbr, pavucontrol, reinstall OS linux, same problem.. but Windows works fine. So the problem is in Linux version of Discord. I'm opening a new support ticket will and let you if something worked out. saludos!

![Captura de pantalla de 2021-07-23 14-01-24 ERROR DISCORD 2](https://user-images.githubusercontent.com/37272894/128447858-a4f1d10a-bff7-481b-81b9-2094f05243a6.png)
