### ISSUE TITLE
Remove or change default IRC support channel

### ISSUE THREAD

**Issue by myfirstnameispaul** [linuxmint/linuxmint#518]
I just had a very bad experience in IRC.

A user in `#linuxmint-help`  named `respawn` is pinging other users and pretending he isn't a spammer, despite the fact that this is a very common spammer technique used by spammers in IRC.

I complained about the user and requested to have the user banned, and the moderator banned me, instead.

This kind of moderation behavior in a built-in default support tool should not be tolerated.

I encourage you to consider changing the moderators or removing the tool from the operating system.
![linuxmint-help](https://user-images.githubusercontent.com/5705007/186910623-e805c288-e07a-4705-94b4-de2d96b16417.png)
![linuxmint-chat](https://user-images.githubusercontent.com/5705007/186910671-75e99f5b-40e3-48fb-b74d-7d6239a666d2.png)

**Comment by myfirstnameispaul** [comment]
I made a post regarding this issue to the Linux Mint Forums and it was removed with a message from a forum moderator that someone has contacted the IRC moderators, but I have no idea where that contact has been made or if it is in a public forum, which it should be in a public forum.

The forum moderator pointed me to a very informative post in the forums regarding IRC rules, that previously I was unaware of:

https://forums.linuxmint.com/viewtopic.php?f=17&t=224270

A reasonable thumbrule for moderators should be when someone is not completely abusive and falling somewhat within a grey area, point them to rules. The instaban from the IRC with no explanation other than a snarky comment ("User banned per user request.") is not acceptable under any circumstance.

Further, the mocking of the event in the chat channel should be not be tolerated from a moderator. I have banned many, and I never used snark or mocked, not even when they taunted me.

Moderators should be held to high standards, especially for a project as visible as Linux Mint.

If the channel, itself, is outside the control of the project, then it should not be a default feature of the operating system.

**Comment by loop-de-r00t** [comment]
Hi there! I'm an IRC-OP on the Spotchat network, an admin on the IRC network that hosts the LM channels.

According to the logs you provided, the user respawn talked in #linuxmint-help 5 times in the 13-minute window you provided. That doesn't seem like spam to me. The user respawn has been around for a long time, and is a long-time helper of the channel. The logs you provided showed they were directing people to #linuxmint-chat to chat instead of using the help channel to chat, as per the rules of the LM Channels.

Further, you were not banned, only kicked. A 'kick' in IRC is when an Op (or moderator in IRC lingo) temporarily removes a user from a channel. A ban is when an Op removes a user and prevents them from rejoining for a certain period of time (default time on the LM channels is 24 hours). You were only kicked, not banned, therefore you were able to rejoin after the kick. 

I understand how this can be confusing for new users. Hope this helps!

**Comment by myfirstnameispaul** [comment]
You are side-stepping the clear issue of how unprofessional  the moderation of the channel is. Moderators should not use snark or mock.

You also ignore the user pinging, which is the negative behavior I originally complained about. It does not matter if a user is "helpful" while trolling, or how long they remained logged in, or generally any of these other metrics when they are engaging in clearly abusive behaviors. Even "kicking" me for complaining about this behavior is not acceptable and based on the snark, I consider to be malicious as it communicates a certain joy in using the ban moderation tool, and frankly really pathetic to be protecting a troll.

Your attempt to state a bunch of data from your logs is not excusing the behavior of pinging. I can see there are many channels I use that if a user pings even once unnecessarily, mods will either admonish or instaban. Pinging is an absolute no-no in any moderated IRC channel except when specifically replying to a user, under which circumstance it is often appreciated and seems to be the reason most users and administrators leave the feature enabled.

I think someone with your experience should already know these things.

My IP address cannot log into the server, even from a different computer and the generic default login settings. I call this a ban.

**Comment by loop-de-r00t** [comment]
I think we may have a miscommunication here.

You are very new to the channels. According to my logs, the first time your nick 'paul' logged on was August 23rd, **3 days ago** from now. Therefore, any assumption you make about how the channels are run, or how other users help in the channels is irrelevant. You have no normal 'behavior' to base your observations on, because you have only been there 3 days. You assume that respawn is spamming, because they are redirecting people to #linuxmint-chat instead of the help channel when they want to chat. This is normal, and a part of the rules. **Just because you don't agree with it, or don't like it, doesn't mean someone is being abusive.**

How other channels are run has no bearing on how the LM channels are run. Each online community does things differently, and nobody expects you (or anyone) to understand how that community works by being there for only 3 days. **I don't blame you for assuming something, because you're a new user, but to call behavior abusive when you have no frame of reference to how that community is run is jumping the gun a little bit.** Please don't assume you know everything after being there for 3 days.

As I said, respawn talked 5 times in a 13-minute window, from the logs **you** provided. That doesn't seem like spam to me, and I think most reasonable people would agree, especially if each of the 5 times they spoke, they did so to direct people who were chatting to go to #linuxmint-chat, as per the rules. I guess I have to repeat myself, since I said the same thing in my first post. I'm not ignoring the pinging, I already gave my reasons as to why I don't think they're spam, and why any reasonable person (who has been there long enough to understand how the community works) would agree.

As I mentioned in my first post, I am an IRCOp, which allows me to view things like network bans. I don't see anything in our network ban list that would match the user 'paul.' I can assure you that no IRCOp banned you today.

**Comment by myfirstnameispaul** [comment]
I log in using SASL (username + password). I did not log in for the first time three days ago. That is the most recent log in from the user account.

HexChat keeps something around 7 days of history in a window, and reviewing the history I can see `respawn` is constantly pinging users, even when replying to a user less than a minute after after the user posts and as the subsequent message.

So your provided information is very incomplete.

My experience on other channels is more than relevant, because it is the observed behavior of the combined experience of many moderators, and on channels that are very mature.

If you are stating that behavior which earns an instaban on most IRC channels is embraced on the Linux Mint IRC, then this further supports my request to either remove the default IRC channel from Linux Mint or move the official support channel some place else.

My general complaint is that the channel moderators are very unprofessional and rude. This is outside of whatever rules you may claim to be following.

You may note that in `#linuxmint-help`, user `respawn` has pinged me unnecessarily. I complained about this behavior and this resulted in an immediate ban from the channel 30 seconds after the complaint. This is the moderator protecting a troll by banning a user who complained after being abused by the troll.

You should also note that in `#linuxmint-chat`, the moderator pinged me to mock me. Utterly unacceptable behavior.

You are attempting to throw out a red herring. I have not made a complaint about the rules of the channel. I have made a complaint that the channel is unacceptably rude and unprofessional and should either be changed to a different channel or removed from the OS.

Please do not use phrases like "reasonable people would agree". What you are doing when you do this is to frame me as someone unreasonable. I find it arrogant and insulting.

You discuss some quantity of messages, again, completely trying to change the topic of my original complaint of pinging users unnecessarily.

**Comment by loop-de-r00t** [comment]
It's clear to me now that this line of conversation isn't going anywhere and isn't a good use of my time. Good bye and good luck. I won't be responding to you further.

**Comment by myfirstnameispaul** [comment]
You did not attempt to address my complaints. At the very least there is no communication, indeed.

**Comment by xenopeek** [comment]
The [IRC Channel Rules](https://forums.linuxmint.com/viewtopic.php?f=17&t=224270) say where to direct complaints and it's not here. This is unrelated to development of Linux Mint so I'm closing this here.
