### ISSUE TITLE
Chromium in Wayland does not enable pipewire RTC = screen sharing does not work

### ISSUE THREAD

**Issue by matejcik** [linuxmint/linuxmint#527]
For Chromium to be able to share your screen under Wayland, it needs experimental pipewire support built-in.
Then you go to `chrome://flags`, toggle the support, and if all goes well, you're able to screencast the same as under X11.

In Mint's build, the relevant flag is missing, because it was not enabled at build time.

This is the same issue as https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1849478, except that one relates to Snap build of chromium.

**Comment by mtwebster** [comment]
Hi, sorry I missed this when you originally filed it.

I originally went by Ubuntu's snap recipe when we started building chromium ourselves (and it was also in Mint 20, where pipewire support was lacking) - I didn't notice that they'd cleared up their issues and enabled it finally.

I've built chromium beta with `rtc_use_pipewire = true` if you'd llike to try it out.  If it's ok I'll enable it on stable builds moving forward. I would back up your profile first since this is a beta (though it seems ok to me).

https://www.dropbox.com/sh/8oadbkjrxdt9rjv/AAB57Q_VkcWXUZd9KKoP0QkYa?dl=0
(Sorry for dropbox, I can't leave a link to the build server here).

![image](https://github.com/linuxmint/linuxmint/assets/262776/9b876383-1330-44e4-8b86-48c9b3220ca3)

**Comment by matejcik** [comment]
thanks! confirming that this works for me out of the box, even without fiddling with the webrtc pipewire flag

**Comment by matejcik** [comment]
any updates?

for now I unfortunately have to revert to stable chromium because I'm seeing some other problems (most likely beta-related), but that means that I'm losing pipewire screencasting again

**Comment by mtwebster** [comment]
The 115 stable release is due out tomorrow, and this will be part of it - I don't like changing things in the middle of a release cycle.

**Comment by matejcik** [comment]
i'm now on 115.0.5790.110~linuxmint1+victoria and pipewire RTC looks like it is working, so thank you and this can probably be closed

**Comment by mtwebster** [comment]
Great, thanks
