### ISSUE TITLE
Syncthingy Flatpak: (background permission revoked SyncThingy might not work as expected!)

### ISSUE THREAD

**Issue by trymeouteh** [linuxmint/linuxmint#530]
I installed Syncthingy as a flatpak and on Mint 21, I cannot change any of the settings in Syncthingy such as have Syncthingy launch on startup and disable notifications. And when I launch the Syncthingy app I get the following error message
```
background permission revoked
SyncThingy might not work as expected!
```
This is not the case on other distros or when I installed Syncthingy on Mint 20. For whatever reason this is an issue with Mint 21. Even the Syncthingy dev mentioned it is an issue with Linux Mint 21 and not Syncthingy

https://github.com/zocker-160/SyncThingy/issues/6#issuecomment-1244815959

**Comment by mtwebster** [comment]
It's because we have not yet implemented some of the portals that flatpaks use (these allow for better integration between flatpaks and normal desktop things.

https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.Background

This has already been reported:
https://github.com/linuxmint/cinnamon-desktop/issues/202

It's on our TODO.
