### ISSUE TITLE
pressing ctrl+alt+f1 deletes user data

### ISSUE THREAD

**Issue by zolstarym** [linuxmint/linuxmint#541]
In my .bashrc file I have HISTSIZE=500000 and HISTFILESIZE=1000000, and it works, but whenever I hit ctrl+alt+f1 and login, the history size resets to 500, deleting everything past that. The virtual console ignores .bashrc settings. It should load the same .bashrc file as any other console session.

**Comment by kj7rrv** [comment]
That is because opening a terminal with Ctrl+Alt+F1 opens a login shell, while a terminal window opens a non-login shell. Putting `source ~/.bashrc` in `~/.bash_profile` (creating that file if needed) should fix this.

**Comment by zolstarym** [comment]
So there is no way for mint to change the default behavior and consolidate the profiles?

**Comment by kj7rrv** [comment]
It might be possible for them to do it by default, but it isn't standard behavior for Linux systems. Login and non-login shells are normally configured differently. Because the normal behavior for Linux is to treat the two types differently, it could be confusing to combine the configuration by default, and there's really no benefit because it's simple to do manually.

**Comment by zolstarym** [comment]
thanks for the info
