### ISSUE TITLE
mint 19 install partition failure

### ISSUE THREAD

**Issue by illumilore** [linuxmint/linuxmint#66]
When installing 19, I get an error during partitioning that stops the installation

The attempt to mount a file system with type vfat in SCSI1 (0,0,0), partition #1 (sda) at /boot/efi failed.
You may resume partitioning from the partitioning menu.

The options go back or continue do nothing.

**Comment by xenopeek** [comment]
Hope you've managed to get past this already. If not, please use the [forums](https://forums.linuxmint.com/viewforum.php?f=46) to get help with troubleshooting on this. See also our [troubleshooting guide](https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/). If during troubleshooting the cause is found to be a component maintained by Linux Mint this can be reopened.
