### ISSUE TITLE
Can't Delete New User Without Reboot

### ISSUE THREAD

**Issue by johnyradio** [linuxmint/linuxmint#68]
Mint 19 xfce (updated):

To replicate:
- Create user in 'Users' app
- Log into new user
- Log out
- Log into old user
- Delete new user in 'Users' app
- Log out

Expectation:
New user login will be gone. 

What happens:
New user login is still visible. 

Fix:
Reboot computer before deleting new user.

alse reported this to xfce
https://bugzilla.xfce.org/show_bug.cgi?id=14634

**Comment by gm10** [comment]
The reason is that your new user's logind session remains in closing state, waiting for all user processes to end. 

You can see active sessions by running `loginctl`.  To kill off the other user's session run this:
> loginctl kill-session **sessionID**
(careful not to kill your own session)

Better yet, to see the processes running for a specific user's session(s) to identify the culprit keeping the session open, run:
> systemd-cgls /user.slice/user-$(id -u **USERNAME**).slice

The usual culprits for stuck processes are the system-config-printer and gnome-keyring. Those are upstream issues.

**Comment by johnyradio** [comment]
Unclear. You're saying this is desirable behavior?

**Comment by gm10** [comment]
> Unclear. You're saying this is desirable behavior?

I didn't evaluate it at all actually, was just explaining the situation.

In my opinion it is 
- undesirable that the Users & Groups tool doesn't check that the deletion actually went through
- desirable that a session remains active waiting for processes to close, but 
- undesirable that there is no timeout
- undesirable that the script in system-config-printer is bugged as well as whatever prevents the gnome-keyring-daemon from exiting cleanly

The Mint devs don't care because it's not their own tools with the problem, that's why they closed this. You have to understand that Mint is little more than a themed Ubuntu with a slightly slimmed down default configuration and a few added scripts. If you're looking for fixes you'll have to look upstream, at least Ubuntu or better yet GNOME.org and freedesktop.org.
