### ISSUE TITLE
after a recent update the mate volume control doesnt work as expected

### ISSUE THREAD

**Issue by gerardbekking** [linuxmint/linuxmint#7]
I might be posting this on the wrong forum but the githup link for the reporting bugs for the mate desktop brought me to the mate repository site,and I could not report a bug there.

After I had an update (around 4-4-2018) The mate-volume-control output works different.
At this update an extra output (line) was added. (i am using linux mint 18 with the mate desktop 1.16.2).
My computer is a HP elitebook 840 with a slim dockingstation type 2013.

In the old set up there where two outputs (laptop)speaker and headphones If you selected headphones you also activated the line out on the docking station and the desktopspeackers would go mute.

In the new setup if you select ¨headphones¨ the speakers and the lineout from the dockingstation are swtched of.
If you select ¨speacker¨ the line out and the headphones are switched of
If you select ¨line¨ the headphones are switched of and the speacker will still be on half the volume and the line out from the docking station also has half the volume  (compared to before the update).

**Comment by xenopeek** [comment]
For help with troubleshooting this issue please use the forums: https://forums.linuxmint.com/viewforum.php?f=48. See our [troubleshooting guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/) for more info. If the cause of the problem turns out to be a bug in Linux Mint we can reopen this issue.
