### ISSUE TITLE
Ecryptfs warning/error on first logon from terminal

### ISSUE THREAD

**Issue by saveriomiroddi** [linuxmint/linuxmint#83]
I've got an ecryptfs warning/error on my first installation; I don't know if this can be ignored or not, however, it's alarming (given the Ubuntu ecryptfs context), so I think it's worth clarifying.

My workflow has been this:

1. Installed Mint on my disk, with encrypted home
2. Booted from disk
3. Immediately switched to terminal 1 (Ctrl+Shift+F1), instead of logging in the DE
4. Logged on

Now I got an error, starting with "Could not find valid key with description ...".

5. I got alarmed, and switched to the DE (Ctrl+Shift+F7)
6. Logged on; I didn't observe any (obvious) problem
7. I switched to terminal 2 (Ctrl+Shift+F2)
8. Logged on

Now I did _not_ observe any warning/error.

Is this something expected? Maybe Mint expects the user to first logon in the DE?

Note that the distro was the MATE version, however, I think this is unrelated to ecryptfs (AFAIK).

**Comment by saveriomiroddi** [comment]
(Update)

I've reinstalled the system (points 1 and 2), then:

3. Logged on in the DE
4. Logged out
5. Switched to terminal 1 (Ctrl+Shift+F1)
6. Logged on

Now I did _not_ observe any error/warning, so the theory that there is an expectation of the user to perform the first absolute logon from the DE may have some grounds (I don't have any ecryptfs knowledge, though).

**Comment by xenopeek** [comment]
eCryptfs implements a stacked filesystem that gets automatically mounted when the user logins through the display manager. When logging in through the virtual console you're seeing your encrypted home directory and would use appropriate eCryptfs command to mount the stacked filesystem so you can look "through it" and see the decrypted home directory as you get when logging in through the display manager.

When logging in through the display manager the user's password unscrambles their mount passphrase into the session keyring and that is used for—transparent to the user and programs—encrypting and decrypting your files on the fly.

You seem to have stumbled upon a papercut in this eCryptfs version; indeed when you first try to login at virtual console you get that somewhat unhelpful error but if you exit and then login a second time on the virtual console you get the helpful message you likely were looking for:
```
Signature not found in user keyring
Perhaps try the interactive 'ecryptfs-mount-private'
```
That command would let you access your files when you've not unscrambled your mount passphrase into the session keyring by logging in through the display manager first.

Consider asking such questions on our forum in the future; you'd get answer swifter because there are more knowledgeable users there to help answer.
