### ISSUE TITLE
Cannon LBP2900 printer not working in Mint 19 and 19.1 Beta

### ISSUE THREAD

**Issue by gatons** [linuxmint/linuxmint#88]
Hello. Some time ago i create post on Linux Mint forum. Please check: https://forums.linuxmint.com/viewtopic.php?f=51&t=279175 Post contain long bug description, also contain my actions, to fix it. Printer work without problems on Ubuntu 18.04, 18.10 and LMDE3.

**Comment by gatons** [comment]
> Hi @gatons @Jildridge,
> 
> The two suspects I have in mind are:
> 
> 1. A missing package (Ubuntu installs recommended packages, Mint only installs dependencies).
> 2. The drivers acting differently based on LSB (if part of the drivers or some package read /etc/lsb-release and is hardcoded to only work with Ubuntu/Debian, well, it will only work with Ubuntu/Debian)..
> 
> I would recommend you test both scenario in a fresh install.
> 
> To test scenario 1, temporarily edit /etc/apt/apt.conf.d/00recommends and set APT::Install-Recommends to "true". You can get the list of installed packages with "dpkg -l", if you diff it with the list you currently have (without recommends) you might be able to identify the difference and point at the culprit. You can also use "apt recommends packagename" to ask Mint to point at missing recommends recursively for a given package name.
> 
> To test scenario 2, backup /etc/lsb-release, and temporarily replace it with /etc/upstream-release/lsb-release. This will identify your Mint box as an Ubuntu 18.04 box for any piece of software looking at LSB.

Make both scenarious. No results.

**Comment by Jildridge** [comment]
@clefebvre Thanks for your helpfulness

However, as @gatons writes
> Make both scenarious. No results. 

I did the same. No success. When checking the printer status finally by typing "captstatusui -P LBP2900"
the monitor persistently keeps on reporting: 'Check the DevicePath of /etc/ccpd.conf'. You can believe me, I checked it countless times with different entries. - I am almost about to give up (My makeshift workaround now will be the creation of a small mint or ubuntu 32 bit partition to use the printer with - since the 32 bit drivers do not make any problems. I have very little hope only for an updated driver from Canon. Actually a shame, because this little piece of hardware does otherwise a great home office job.

@Tsoccerguy3 Thanks for your hint.
I tried to  get the printer working by installing the capt drivers offered there. No way for this printer LBP2900. Anyway, good to know about that page for future times.

**Comment by gatons** [comment]
ok. find the source of problem. problem is with cups-filters package :)

find "[Client 20] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)" in cups error log

Linux Mint 19.1 Cinnamon 64bit
Printer Cannon LBP 2900 (32-bit driver version)

Reinstall cups-filters package, restart cups and ccpd services. Printer works.

Now try restarting my PC. After that printer not works again :)

Repat described reinstall process and printer works again. What i need to do, to not repeat cups-filters reinstall process afre PC restart? :D

**Comment by gatons** [comment]
Yesterday make a small experiment: install Ubuntu 18.04 and add Canon LBP 2900 printer. Printer works. After that add Linux Mint repos and upgrade needed system core packages... After that get print error and can't print. Conclusion: something wrong in Linux Mint core packages, that causes this printing error.

**Comment by gatons** [comment]
Solved after using command:

echo Y > /sys/module/usbcore/parameters/old_scheme_first

**Comment by Jildridge** [comment]
Thanks @gatons  for your effort in this case and this suggestion. 

I tried it. However I still can't get the printer running unter mint 19 - 64 bit. (captstatusui error: 'Check the DevicePath of /etc/ccpd.conf'). I tried it in combination with the original installation advice in Canon's install-manual. May I ask by what combination of installation routines you use this workaround, since there are many different advices for installation to be found in the internet. Maybe you can post a link.

Thanks

**Comment by gatons** [comment]
@Jildridge in my case device recognized on port /dev/usb/lp0. All other setup options i do, how described in https://riku.titanix.net/wordpress/canon-2900-working-on-linux/

After that i create file /etc/rc.local and put following:

#!/bin/bash
echo Y > /sys/module/usbcore/parameters/old_scheme_first

/etc/init.d/ccpd stop
/etc/init.d/ccpd start

Save file and make it as executing file to start this command every time, when computer restarts.

**Comment by xenopeek** [comment]
Thanks for detailing your solution to this issue. As those components aren't developed or maintained by Linux Mint I think we can close this here.
